---
title: "Sex Ratio"
author: "В. М. Хайтов"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)

opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(readxl)
library(mgcv)
library(ggplot2)
library(cowplot)
library(gratia)
library(reshape2)
library(dplyr)
library(broom)
library(stringr)
library(lubridate)
library(patchwork)
library(vegan)


theme_set(theme_bw())

```




```{r}

zub_empty <- read_excel("Data/Зубатка_питание2001-2023.xlsx", sheet = "All")

zub_empty <- 
  zub_empty %>% 
  mutate(Date = paste(Date, "/", Year, sep = ""), Sex = factor(Sex))

zub_empty$Date <- as.Date(zub_empty$Date, format ="%d/%m/%Y") 

zub_empty$DOY <- yday(zub_empty$Date)

zub_empty <- 
  zub_empty %>% 
  mutate(Sex_Outcome = ifelse(Sex == "female", 1, 0)) 
  

```


Вот модель для вероятности встретить самок (весь материал, то есть и пустые и полные кишечники)

```{r, echo=TRUE}

mod_sex <- gam(Sex_Outcome  ~ s(DOY, bs = "cr", k = 6) + s(Year, bs = "cr", k = 6), family = "binomial", data = zub_empty)

```



Во результаты подбора этой модели 

```{r}
kable(tidy(mod_sex)[,-3], caption = "Таблица +. Описание аддиивной модели, описвающей сезонную и многолетнюю динамику доли самок в популяции")

```

Никаких значимых изменений в соотношении полов не выявлено ни в течение сезонов, ни в течение многолетнего периода наблюдений.

