---
title: "Планируемое расположение точек мониторинга"
author: "В. М. Хайтов"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)

opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```



```{r}
library(ggmap)
library(mapproj)
library(maps)
library(rgeos) #этот пакет содержит какую-то хрень, которая позволяет обойти проблему пр чтении фалов средствами maptools. 
#Att! Этот пакет должен быть загружен до maptools
library(mapdata)
library(maptools) # Rgshhs
library(PBSmapping)
library(sf)


library(readxl)
library(dplyr)
library(cowplot)
library(png)
library(reshape2)
library(tibble)

library(mgcv)
library(vegan)

```



```{r}

Fin_df <- read.csv("Data/Obskaya_bay_map.csv") # Map poligones

# Basic map layer####################

theme_set(theme_bw())



Pl_Finnish_Gulf <- 
  ggplot(Fin_df, aes(x=long, y=lat, group=group)) +
  geom_polygon(fill = "gray90", colour = "gray20") + 
  theme(axis.title.x = element_blank(),  axis.title.y = element_blank(), plot.background = element_blank(), panel.border = element_blank(), panel.grid = element_blank()) + 
  theme(axis.text.x =element_blank(), axis.text.y= element_blank()) + 
  theme(axis.ticks = element_blank()) 


```

```{r}

# Data reading
stations <- read.csv("Data/predictors.csv")

points <- stations %>% select(Station,Lat, Long) 

names(points) <- c("Station", "lat", "long")

```

```{r}
points_sf <- st_as_sf(points, coords = c("long", "lat"), crs = 4326 )

# load("Data/Finnish_gulf_South.RData")

# point_in_pol <- as.numeric(st_within(points_sf, map))

# stations_on_land <- points %>% filter(point_in_pol == 1)

# load("Data/Finnish_gulf.RData")

# point_in_pol <- as.numeric(st_within(points_sf, map))
```





```{r }

work_area <- read_sf(dsn = "Data/Observation_stationaries.kml")

```




```{r fig.cap="**Рисунок. ** Расположение станций 2019-2021 гг, находящихся в районе рабочего полигона "}

work_polygon_sf <- st_as_sf(work_area, coords = c("long","lat"), crs = 4326)

points_in_work_polygon <- points %>% filter(as.numeric(st_within(points_sf, work_polygon_sf)) == 1) 

work_polygon_coordinates <- as.data.frame(st_coordinates(work_polygon_sf)) %>% select(1, 2)

names(work_polygon_coordinates) <- c("long", "lat")  

```


```{r}
points_23 <- read_excel("Data/points_2023.xlsx")
```

```{r fig.cap="**Рисунок. ** Станции, запланированные на 2023 год"}
Pl_stations + 
  geom_point(data = points_23, aes(color = Zone))

 
```


```{r}
echo_area_23 <- read_excel("Data/echo_scanning_2023.xlsx")




```

```{r fig.cap="**Рисунок. ** Полигоны многолучевого эхолотирования и ГЛБО. Везде, кроме полигона №4, длина составляет 1 км."}
Pl_stations + 
  geom_point(data = points_23, aes(color = Zone)) +
  geom_segment(data = echo_area_23, aes(x = long, y = lat, xend = long, yend = lat + Length/111), size = 2)
```



Координаты предполагаемых станций
```{r}
kable(points_23)
```


Координаты точек начала полигона для многолучевого эхолотирования и длина полигона (км)
```{r}
kable(echo_area_23)
```

