---
title: ""
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = TRUE, message = F)
```


```{r}
library(readxl)
library(ggplot2)
library(dplyr)
library(reshape2)
library(tidyr)
```


```{r}
phen <- read_excel("Data/Phenology_2021.xlsx", sheet = "phenology")


phen %>% select(Year, Temp_dynamics_type, Calanus_50_perc, Pseudocalanus_50_perc, Acartia_50_perc, Centropages_50_perc, Temora_50_perc, Microsetella_50_perc, Oithona_50_perc) %>% melt(id.vars = c("Year", "Temp_dynamics_type")) %>% filter(!is.na(Temp_dynamics_type)) %>% filter(Temp_dynamics_type != 5) %>%
  ggplot(., aes(x = factor(Temp_dynamics_type), y = value)) + geom_boxplot() + facet_wrap(~variable) + labs(x= "Type of temperature dynamics", y = "Julian day")


phen %>% select(Year, Temp_dynamics_type, Calanus_N, Pseudocalanus_N, Acartia_N, Centropages_N, Temora_N, Microsetella_N, Oithona_N) %>% melt(id.vars = c("Year", "Temp_dynamics_type")) %>% filter(!is.na(Temp_dynamics_type)) %>% filter(Temp_dynamics_type != 5) %>% 
  ggplot(., aes(x = factor(Temp_dynamics_type), y = log(value) )) + geom_boxplot() + facet_wrap(~variable) + labs(x= "Type of temperature dynamics", y = "Log(N)")


```

