---
title: "Оценка потенциального влиния массовых учетов на вероятность гибели кладок гаги обыкновенной"
author: "В. М. Хайтов"
output: 
      word_document:
                reference_docx: Letopis_template.docx
                fig_width: 5
                fig_height: 5
abstract: |
    **Хайтов В. М. Оценка потенциального влияния массовых учетов на вероятность гибели кладок гаги обыкновенной** // Марченков А.В. (ред.) Летопись природы Кадалакшского заповедника за 2022 год (ежегодный отчет). Кандалакша. Т.1 (Летопись природы Кандалакшского заповедника, кн. ++)
    ++++++++++
    
    **Khaitov V.M.   Assessment of the potential impact of mass counts on the probability of mortality of common eider clutches** // Marchenkov A. V. (ed.)  The Chronicle of Nature by the Kandalaksha Reserve for 2022 (Annual report).  Kandalaksha. V.1. (The Chronicle of Nature by the Kandalaksha Reserve, Book N ++)
    
    Based on the data on the water test of the degree of egg incubation, we reconstruct the timing of the start of nesting on different islands of the Kandalaksha Bay during the nesting period of 2022. 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(reshape2)
library(knitr)
library(pander)
library(readxl)
library(dplyr)
library(ggplot2)
library(cowplot)
library(lubridate)
library(ggmap)
library(stringr)

library(flextable)


editor <- "Марченков А.В."
editor_eng <- "Marchenkov A.V."

Year <- 2022

# Функция, задающая нумерацию рисунков

figRef <- local({
    tag <- numeric()
    created <- logical()
    used <- logical()
    function(label, caption, prefix = options("figcap.prefix"), 
        sep = options("figcap.sep"), prefix.highlight = options("figcap.prefix.highlight")) {
        i <- which(names(tag) == label)
        if (length(i) == 0) {
            i <- length(tag) + 1
            tag <<- c(tag, i)
            names(tag)[length(tag)] <<- label
            used <<- c(used, FALSE)
            names(used)[length(used)] <<- label
            created <<- c(created, FALSE)
            names(created)[length(created)] <<- label
        }
        if (!missing(caption)) {
            created[label] <<- TRUE
            paste0(prefix.highlight, prefix, " ", i, sep, prefix.highlight, 
                " ", caption)
        } else {
            used[label] <<- TRUE
            paste(prefix, tag[label])
        }
    }
})

options(figcap.prefix = "Рисунок", figcap.sep = ".", figcap.prefix.highlight = "**")

theme_set(theme_bw())

```

```{r}
# Калькулятор даты откладки яиц по данным водного теста
df =  read_excel("Data/water_test_calculator.xlsx")

wt_calculator <- function(df){
  require(readxl)
  require(dplyr)
  wt_calc <- read_excel("Data/water_test_calculator.xlsx")
  wt_calc$Value <- as.numeric(wt_calc$Value)
  wt_calc_angle <- wt_calc %>% filter(Type == "Angle")
  wt_calc_diam <- wt_calc %>% filter(Type == "Diametr" & Value !=0)
  Mod_angle <- lm(Day ~ Value, data = wt_calc_angle)
  Mod_diam <- lm(Day ~ Value, data =  wt_calc_diam)
  df <- 
  df %>% mutate(Day = case_when(
    Type == "Angle" ~ round(predict(Mod_angle, newdata = df)),
    Type == "Diametr" & Value <=5 ~ 11,
    Type == "Diametr" & Value > 5 ~ round(predict(Mod_diam, newdata = df)),
    Type == "Pierced" ~ 25))
  df$Day
}




###

wtest <- read_excel("Data/water_test_data_base_2014_2022.xlsx", na = "NA")


# Вычисление дня откладки яйца

wtest$Day <- as.numeric(wt_calculator(wtest))

wtest$Day[wtest$Type %in% c("Pierced","Hatching" )] <- 45

wtest <- wtest %>% mutate(Year = year(wtest$Date))


```




```{r}

Nest_count <- 
wtest %>% group_by(ID) %>% 
  summarise(Day_max = max(Day)) %>% 
  mutate(Group = case_when(
  Day_max <= 14 ~ "First",
  Day_max > 14 ~ "Second"
  )) %>% 
  filter(!is.na(Group)) %>% 
  group_by(Group) %>% 
  summarise(N_nest = n()) %>% 
  mutate(Abandoned = N_nest * c(0.21, 0.03), Broken = N_nest*c(0.11, 0))



Abandoned <- round(sum(Nest_count$Abandoned)/sum(Nest_count$N_nest) * 100, 2)

Broken <- round(sum(Nest_count$Broken)/sum(Nest_count$N_nest) * 100, 2)

```

