---
title: "Взаимоотношения Oithona и Microsetella"
author: "Вадим Хайтов"
date: ''
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```



```{r}
library(reshape2)
library(dplyr)
library(stringr)
library(ggplot2)
library(mgcv)
library(gridExtra)
library(broom)
library(tidyr)
library(car)
library(vegan)
library(ggvegan)



theme_set(theme_bw())

cop_init_100 <- read.table("Data/Oithona_Microsetella_100_mkm.csv", sep = ",", header = T)


cop100 <- melt(cop_init_100, id.vars = c("Day","Month","Year","Date"), variable.name = "Stage", value.name = "N") 



cop100$Depth[str_detect(as.character(cop100$Stage), "_1")] <- "0_10"  
cop100$Depth[str_detect(as.character(cop100$Stage), "_25")] <- "0_25"  
cop100$Depth[str_detect(as.character(cop100$Stage), "_3")] <- "25_bottom" 
cop100$Depth[is.na(cop100$Depth)] <- "10_25" 

cop100$Stage2[str_detect(as.character(cop100$Stage), "_F_")] <- "Female"
cop100$Stage2[str_detect(as.character(cop100$Stage), "_M_")] <- "Male"
cop100$Stage2[str_detect(as.character(cop100$Stage), "_C_")] <- "Cop."
cop100$Stage2[str_detect(as.character(cop100$Stage), "_J_")] <- "Juv."
cop100$Stage2[str_detect(as.character(cop100$Stage), "_A_")] <- "Adult"
cop100$Stage2[str_detect(as.character(cop100$Stage), "_N_")] <- "Nauplii"
cop100$Stage2[is.na(cop100$Stage2)] <- "Total"




cop100$Sp[str_detect(as.character(cop100$Stage), "OITO")] <- "Oithona"
cop100$Sp[str_detect(as.character(cop100$Stage), "MIC")] <- "Microsetella"



cop100$Stage2 <- factor(cop100$Stage2, levels = c( "Adult", "Male", "Female", "Nauplii", "Juv.", "Cop."))




#Remove all cases with NA in Abundance
cop100 <- cop100[! is.na(cop100$N), ]

cop100$Sp <- factor(cop100$Sp)


#Construct the variable vith date of sample
cop100$Date_text <- with(cop100, paste(Day,Month,Year, sep = "-"))

cop100$Date <- as.POSIXct(as.Date(cop100$Date_text, format = "%d-%m-%Y"))



#Combine Males and Females in one category 
cop100$Stage3 <- as.character(cop100$Stage2)

cop100$Stage3[cop100$Stage3 %in% c("Male", "Female", "Adult")] <- "Adult"

cop100$Stage3 <- as.factor(cop100$Stage3)

#Ordering stages 
cop100$Stage3 <- factor(cop100$Stage3, levels = c("Adult", "Nauplii", "Juv.", "Cop.") )

# table(cop100$Stage3, cop100$Sp)
# unique(cop100$Stage3)


#Constructing date of sample as Day from yar beginning

cop100$DOY <- as.numeric(strftime(cop100$Date, format = "%j"))


# Log transformation for abundance

cop100$Log_N <- log(cop100$N + 1)


# Вторичная гидрология. Усреденные данные, полученные в том числе и из интернета.

env <- read.table("Data/env_gap_filled_short.csv", sep = ",", header = T)




#Первичная гидрология, снятая при отборе проб

hydr100_init <- read.table("Data/hydrology_100_мкм.csv", sep = ",", header = T)


hydr100 <- melt(hydr100_init, id.vars = c("Day","Month","Year"), variable.name = "Parametr", value.name = "Value") 

hydr100$Depth[str_detect(as.character(hydr100$Parametr), "_0.10")] <- "0_10"  
hydr100$Depth[str_detect(as.character(hydr100$Parametr), "_10.25")] <- "10_25"  
hydr100$Depth[str_detect(as.character(hydr100$Parametr), "_25.60")] <- "25_bottom" 
hydr100$Depth[str_detect(as.character(hydr100$Parametr), "_0.60")] <- "0_bottom" 
hydr100$Depth[str_detect(as.character(hydr100$Parametr), "_0.25")] <- "0_25" 

hydr100$Param <- NA

hydr100$Param[str_detect(as.character(hydr100$Parametr), "t_")] <- "Temp" 
hydr100$Param[str_detect(as.character(hydr100$Parametr), "S_")] <- "Sal" 
hydr100$Param[str_detect(as.character(hydr100$Parametr), "Chl_")] <- "Chl" 


hydr100$Date_text <- with(hydr100, paste(Day,Month,Year, sep = "-"))

hydr100$Date <- as.POSIXct(as.Date(hydr100$Date_text, format = "%d-%m-%Y"))

hydr100$DOY <- as.numeric(strftime(hydr100$Date, format = "%j"))


```


```{r}
# Переводим данные по обилию в матрицу, пригодную для сса

cop100_N <- dcast(cop100, formula = Date_text + Depth  ~ Sp + Stage3, value.var = "N", fun.aggregate = sum )

hydr100_Param <- dcast(hydr100, formula = Date_text + Depth  ~ Param, value.var = "Value", fun.aggregate = mean)

hydr100_Param$Depth2 <- 
  case_when(hydr100_Param$Depth ==  "0_10" ~ 5.5,
           hydr100_Param$Depth == "10_25" ~ 17.5,
           hydr100_Param$Depth == "25_bottom" ~ 45)


cop100_N_env <- merge(cop100_N, hydr100_Param )



cop100_N_env <- cop100_N_env[complete.cases(cop100_N_env),]


```

```{r}

# CCA RDA

N_100 <- cop100_N_env %>% select(-c(Date_text, Depth, Chl,  Sal, Temp, Depth2))

cop100_N_env_2 <- cop100_N_env %>% filter(rowSums(N_100) != 0)

N_100_2 <- cop100_N_env_2 %>% select(-c(Date_text, Depth, Chl,  Sal, Temp, Depth2))


mod_cca <- cca(N_100_2  ~ Chl +  Sal + Temp + Depth2, data = cop100_N_env_2)


# anova(mod_cca)
# anova(mod_cca, by = "margin")
# 
# anova(mod_cca, by = "axis")

plot(mod_cca, display = c("sp", "cn" ), choices = c(1, 2), scaling = "species")







```



