---
title: "Divergence in the ecological space between cryptic blue mussel species in the White Sea: towards to species distribution modelling"
author: "**V. M. Khaitov, A. A. Zaychikova, P. Y. Safonov, M. V. Katolikova, M. V. Ivanov, P. P. Strelkov**"
output:
  # html_document
  word_document:
    reference_docx: article_template.docx
    fig_width: 8
    fig_height: 5
# bibliography: Astred_english_Bibliografy_abriviated.bib
# csl: marine-biology.csl
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, dpi = 300)
options(knitr.kable.NA = '')
```

```{r}
## Packages ######

library(ggplot2)
library(lme4)
library(glmmADMB)
library(reshape2)
library(dplyr)
library(patchwork)
library(broom)
library(broom.mixed)
library(tidyr)
library(readxl)
library(mgcv)
library(gratia)
library(flextable)
library(cowplot)

theme_set(theme_bw())

```

```{r training_data}
##### Data reading
myt_full <- read_excel(path = "data/myt_full_2024.xlsx", sheet = "Samples")


ports <- data.frame(Shore = c("Kand", "Karel", "Kand", "Karel", "Karel", "Karel"), Port = c("Kandalaksha", "Vitino", "Umba", "Chupa", "Keret", "Kovda"), Status = c("Active", "Active", "Abandoned", "Abandoned", "Abandoned", "Abandoned"  ), Lat = c(67.137283, 67.076570,  66.677970, 66.269964, 66.294178, 66.696754), Lon = c(32.407995, 32.333630, 34.357655, 33.069534, 33.640656, 32.875396))


# sites_fetch_df <- read.table("data/Distred_samples_fetch_values_2023.csv", sep = ",", header = T)
# 
# sites_fetch_df[,1:5] <- sites_fetch_df[,1:5]/1000 

# Сonventional coordinates of the top of the Kandalaksha Bay
Shore_boundary = c(67.162360, 32.332371)


river_full <- read.table("data/Rivers_2021.csv", sep = ",", header = T)

```



```{r Boundary_of_Ptros_between_MT_and_ME_dominated_sites}

boundary = 0.5

```




```{r}
myt_full <- 
  myt_full %>%
  mutate(Ptros =  exp(-2.4 + 5.4 * Prop_T)/(1 + exp(-2.4 + 5.4 * Prop_T)) ) %>% 
  mutate(Log_Min_dist_port = log(Min_dist_port),
         Log_Min_dist_river = log(Min_dist_river),
         Log_Average_Fetch = log(Average_Fetch),
         Log_Fetch = log(Fetch)) %>% 
  mutate(Mt_dominated = ifelse(Ptros > boundary, 1, 0))
  
```






```{r training_data_housekeepimg}

myt_full$Position <- factor(myt_full$Position)

myt_full$Position <- relevel(myt_full$Position, ref = "Bottom")

myt_full$Port_Status <- factor(myt_full$Port_Status)

myt_full$Port_Status <- relevel(myt_full$Port_Status, ref = "Abandoned")

myt_full$River_Size <- factor(myt_full$River_Size)

myt_full$River_Size <- relevel(myt_full$River_Size, ref = "Small")

myt_full$Site <- factor(myt_full$Site)

# names(myt_full)
```




```{r training_data_sites}
myt_site <- myt_full %>% 
  group_by(Site) %>% 
  # select(Lat, Lon, N_T, N_E, Salinity, Min_dist_river, River, River_Size, Min_dist_river_Large, Min_dist_port, Port, Port_Status, Average_Fetch, Fetch, Dist_cut) %>% 
  summarise(Lat = mean(Lat), Lon = mean(Lon), N_T = sum(N_T), N_E = sum(N_E), Salinity = mean(Salinity), Min_dist_river = mean(Min_dist_river), River = unique(River), River_Size = unique(River_Size), Min_dist_river_Large = mean(Min_dist_river_Large),  Min_dist_port = mean(Min_dist_port), Port = unique(Port), Port_Status = unique(Port_Status), Average_Fetch = mean(Average_Fetch), Fetch = mean(Fetch), Dist_cut = mean(Dist_cut)) %>% 
  mutate(Prop_T = N_T/(N_T+N_E)) %>% 
  mutate(Ptros = exp(-2.4 + 5.4 * Prop_T)/(1 + exp(-2.4 + 5.4 * Prop_T)))

```




```{r training_data_sites_substrates }

myt_site_substr <-
  myt_full %>%
  group_by(Site, Position) %>%
  summarise(N_E = sum(N_E), N_T = sum(N_T),
        Salinity = mean(Salinity),
        Min_dist_river = mean(Min_dist_river),
        River_Size = unique(River_Size),
        Average_Fetch = mean(Average_Fetch),
        Fetch = mean(Fetch),
        Min_dist_port = mean(Min_dist_port),
        Port_Status = unique(Port_Status),
        Lon = mean(Lon),
        Lat = mean(Lat)) %>%
  mutate(Prop_T = N_T/(N_T + N_E)) %>%
  mutate(Ptros =  exp(-2.4 + 5.4 * Prop_T)/(1 + exp(-2.4 + 5.4 * Prop_T))) %>%  
  mutate(Mt_dominated = ifelse(Ptros > boundary, 1, 0))


myt_site_substr <- 
  myt_site_substr %>% 
  mutate(Log_Min_dist_port = log(Min_dist_port),
         Log_Min_dist_river = log(Min_dist_river),
         Log_Fetch = log(Fetch))

```



```{r myt_testing_data_set}
myt_test <- read_excel("data/myt_White_Sea_testing_data_set.xlsx")

myt_test <-
  myt_test %>% 
  filter(Exclude == 0)

myt_test_site <- myt_test %>% group_by(Site, Position) %>%  
  summarise(N_E = sum(N_E), N_T = sum(N_T),
        Salinity = mean(Salinity, na.rm = T),
        Min_dist_river = mean(Min_dist_river),
        River_Size = unique(River_Size),
        Average_Fetch = mean(Average_Fetch),
        Fetch = mean(Fetch),
        Min_dist_port = mean(Min_dist_port),
        Port_Status = unique(Port_Status),
        Lon = mean(Lon),
        Lat = mean(Lat)) %>%
  mutate(Prop_T = N_T/(N_T + N_E)) %>%
  mutate(Fi_T = 2*asin(sqrt(Prop_T))*180/pi) %>%
  mutate(Ptros = exp(-2.4 + 5.4 * Prop_T)/(1 + exp(-2.4 + 5.4 * Prop_T)),
         Fi_tros = 2*asin(sqrt(Ptros))*180/pi) %>% 
  mutate(Mt_dominated = ifelse(Ptros > boundary, 1, 0))

myt_test_site <- 
  myt_test_site %>% 
  mutate(Log_Min_dist_port = log(Min_dist_port),
         Log_Min_dist_river = log(Min_dist_river),
         Log_Average_Fetch = log(Average_Fetch),
         Log_Fetch = log(Fetch))

```





```{r Tyuva_testing_data_set}
tuv <- read_excel("data/TuMyt_2009_2010_for_SDM.xlsx")

tuv <- tuv %>% mutate(Mt_dominated  = ifelse(Ptros_predicted > boundary, 1, 0))

# tuv <- tuv %>% filter(Depth > -1.5)
tuv <-
  tuv %>% mutate(Ptros_WSBL = exp(-2.4 + 5.4 * PT)/(1 + exp(-2.4 + 5.4 * PT)),
                 Ptros = exp(-2.3 + 3.3*PT)  /  (1 +  exp(-2.3 + 3.3*PT)))

tuv <- 
  tuv %>% 
  mutate(Log_Min_dist_port = log(Min_dist_port),
         Log_Min_dist_river = log(Min_dist_river + 1),
         Log_Average_Fetch = log(Average_Fetch),
         Log_Fetch = log(Fetch))
```


```{r}

kola <- read_excel("data/Testing_data_from_Khaitov_et_al_2021.xlsx", sheet = "S1 Kola samples")
kola$Port_Status <- factor(kola$Port_Status)
kola$Position <- "Bottom"
# kola$Position <- "Algae"

kola$Position <- factor(kola$Position)
kola$River_Size <- factor(kola$River_Size)

kola$Log_Fetch <- log(kola$Fetch)
kola$Log_Min_dist_port <- log(kola$Min_dist_port)
kola$Log_Min_dist_river <- log(kola$Min_dist_river)

kola <- 
  kola %>% 
  mutate(Ptros = ifelse(Sample_set == "BL", exp(-2.4 + 5.4 * PT)/(1 + exp(-2.4 + 5.4 * PT)), 
         exp(-3.9 + 5.0 * PT)/(1 + exp(-3.9 + 5.0 * PT)))) %>% 
  mutate(Mt_dominated = ifelse(Ptros > boundary, 1, 0)) %>% 
  filter(Region == "Kola Bay")

```




```{r material_discription_values}
Total_samples <- nrow(myt_full)
Total_site <- length(unique(myt_full$Site))
Site_published <- length(unique(myt_full$Site [myt_full$Source != "Original"]))

Total_N <- sum(myt_full$N_T) + sum(myt_full$N_E)
Min_N <- min(myt_full$N_T + myt_full$N_E)
Max_N <- max(myt_full$N_T + myt_full$N_E)
Mean_N <- mean(myt_full$N_T + myt_full$N_E)
SD_N <- sd(myt_full$N_T + myt_full$N_E)


```


```{r incomplete_training_sites}
incomplete_sites <- c("Bersakol", "Kovd", "Youzh", "Kuz1", "Chup1", "Chup2", "Chup4", "Chup3", "Por", "Umb", "Gridshel", "Gridexp")

# myt_full <- myt_full %>% filter(! Site %in% incomplete_sites)

```




```{r}
library(officer)
params <- read_excel("data/Model_parameters_discription.xlsx")

params$Range[2] <- paste("Algae VS Bottom")


params$Range[4] <- paste(min(myt_full$Salinity),"-", max(myt_full$Salinity), " (", median(myt_full$Salinity), ")", sep = "") 

params$Range[5] <- paste(round(min(myt_full$Min_dist_river), 1),"-", round(max(myt_full$Min_dist_river), 1), " (", round(median(myt_full$Min_dist_river), 1), ")", sep = "") 

params$Range[6] <- paste("Small VS Large")

params$Range[8] <- paste(round(min(myt_full$Min_dist_port), 1),"-", round(max(myt_full$Min_dist_port), 1), " (", round(median(myt_full$Min_dist_port), 1), ")", sep = "") 

params$Range[9] <- paste("Active VS Abandoned")

params$Range[11] <- paste(round(min(myt_full$Average_Fetch), 1),"-", round(max(myt_full$Average_Fetch), 1), " (", round(median(myt_full$Average_Fetch), 1), ")", sep = "") 


ft <- flextable(params)

column_name <- c(
  "Environmental parameter/ model predictor",
  "Type",
  "Explanation",
  "Range (median) in the data" 
)

ft <-
ft %>% 
set_header_labels(values = column_name) %>% 
  set_caption(caption = "Table ++. Environmental parameters used for the analysis")

ft %>% 
  merge_at(i = 1) %>%
  merge_at(i = 3) %>%
  merge_at(i = 7) %>%
  merge_at(i = 10) %>%
  align(i = c(1, 3, 7, 10), align = "center") %>%
  italic(i = c(1, 3, 7, 10)) %>% 
  border(i = c(1, 3, 7, 10), border.bottom =  fp_border(color = "black")) %>% 
  width(j =  c(1, 2,3,4), width = c(3, 2, 10, 4), unit = "cm")
  
# %>% 
#   autofit()

```



```{r Models_calculations}

Mod_gam <- gam(Ptros ~ s(Salinity, bs = "cs") + s(Log_Min_dist_river, bs = "cs") + s(Log_Fetch, bs = "cs") + s(Log_Min_dist_port, bs = "cs") + Position + River_Size + Port_Status + s(Site, k = Total_site, bs = "re"), method = "REML", family = betar(link = "logit"), data = myt_full )

# summary(Mod_gam)

# Mod_gam_ML <- gam(Ptros ~ s(Salinity, bs = "cs") + s(Log_Min_dist_river, bs = "cs") + s(Log_Fetch, bs = "cs") + s(Log_Min_dist_port, bs = "cs") + Position + River_Size + Port_Status + s(Site, k = Total_site, bs = "re"), method = "ML", family = betar(link = "logit"), data = myt_full )
# 
# Mod_gam_ML2 <- gam(Ptros ~ s(Salinity, bs = "cs") + s(Log_Fetch, bs = "cs") + s(Log_Min_dist_port, bs = "cs") + Position + River_Size + Port_Status + s(Site, k = Total_site, bs = "re"), method = "ML", family = betar(link = "logit"), data = myt_full )
# 
# 
# Mod_gam_ML3 <- gam(Ptros ~ s(Salinity, bs = "cs") + s(Log_Min_dist_port, bs = "cs") + Position + River_Size + Port_Status + s(Site, k = Total_site, bs = "re"), method = "ML", family = betar(link = "logit"), data = myt_full )
# 
# Mod_gam_ML4 <- gam(Ptros ~ s(Log_Min_dist_port, bs = "cs") + Position + River_Size + Port_Status + s(Site, k = Total_site, bs = "re"), method = "ML", family = betar(link = "logit"), data = myt_full )
# 
# Mod_gam_ML5 <- gam(Ptros ~ Position + River_Size + Port_Status + s(Site, k = Total_site, bs = "re"), method = "ML", family = betar(link = "logit"), data = myt_full )
# 
# Mod_gam_ML6 <- gam(Ptros ~ Position + Port_Status + s(Site, k = Total_site, bs = "re"), method = "ML", family = betar(link = "logit"), data = myt_full )
# 
# Mod_gam_ML7 <- gam(Ptros ~ Position + s(Site, k = Total_site, bs = "re"), method = "ML", family = betar(link = "logit"), data = myt_full )
# 
# Mod_gam_ML8 <- gam(Ptros ~ s(Site, k = Total_site, bs = "re"), method = "ML", family = betar(link = "logit"), data = myt_full )


# summary(Mod_gam_ML7)

# AIC(Mod_gam_ML, Mod_gam_ML2, Mod_gam_ML3, Mod_gam_ML4, Mod_gam_ML5, Mod_gam_ML6, Mod_gam_ML7, Mod_gam_ML8)
# AIC(Mod_gam_ML, Mod_gam_reduced_ML)

# appraise(Mod_gam)

# appraise(Mod_gam_reduced)

# summary(Mod_gam)

# summary(Mod_gam_reduced)

# draw(Mod_gam, residuals = T)

```

```{r Model_prediction}
logit_back <- function(x) exp(x)/(1 + exp(x)) 

# Smoothers estimations

sm <- smooth_estimates(Mod_gam) %>%
  add_confint()

sm <- sm %>% 
  mutate(Pi = logit_back(.estimate + coef(Mod_gam)[1]), 
         CI_Pi_low = logit_back(.lower_ci + coef(Mod_gam)[1]),
         CI_Pi_up = logit_back(.upper_ci + coef(Mod_gam)[1]))

myt_full <- myt_full %>% 
  add_partial_residuals(Mod_gam)

# Recalculation of smoothers into probability
myt_full <- 
  myt_full %>% 
  mutate(Pi_Salinity = logit_back(`s(Salinity)` + coef(Mod_gam)[1]),
         Pi_Min_dist_river = logit_back(`s(Log_Min_dist_river)` + coef(Mod_gam)[1]),
         Pi_Average_Fetch = logit_back(`s(Log_Fetch)` + coef(Mod_gam)[1]),
         Pi_Min_dist_port = logit_back(`s(Log_Min_dist_port)` + coef(Mod_gam)[1]))



```


```{r Smoother_predictions_figures}
#Predicted values in the terms of smoothers

Pl_sal_smoother <-
  sm %>%
  filter(.smooth == "s(Salinity)") %>%
  ggplot() +
  geom_point(aes(x = Salinity, y = `s(Salinity)`, color = Position),
             data = myt_full, cex = 1, colour = "steelblue3") +
  geom_rug(aes(x = Salinity),
           data = myt_full,
           sides = "b", length = grid::unit(0.02, "npc")) +
  geom_ribbon(aes(ymin = .lower_ci, ymax = .upper_ci, x = Salinity),
              alpha = 0.2) +
  geom_line(aes(x = Salinity, y = .estimate), lwd = 1) +
  labs(y = "Partial effect", x = "Salinity") +
  geom_hline(yintercept = 0, linetype = 2) +
  theme_bw()


Pl_riv_dist_smoother <- 
    sm %>%
  filter(.smooth == "s(Log_Min_dist_river)") %>%
  ggplot() +
  geom_point(aes(x = Log_Min_dist_river, y = `s(Log_Min_dist_river)`, color = Position),
             data = myt_full, cex = 1, colour = "steelblue3") +
  geom_rug(aes(x = (Log_Min_dist_river)),
           data = myt_full,
           sides = "b", length = grid::unit(0.02, "npc")) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, x = Log_Min_dist_river),
              alpha = 0.2) +
    geom_line(aes(x = Log_Min_dist_river, y = est), lwd = 1) +
  labs(y = "Partial effect", x = "Log Distance to the nearest river (km)") +
  geom_hline(yintercept = 0, linetype = 2) +
  theme_bw()
# +
#   ylim(-0.5, 0.5)



  

Pl_port_dist_smoother <-
     sm %>%
  filter(.smooth == "s(Log_Min_dist_port)") %>%
  ggplot() +
  geom_point(aes(x = Log_Min_dist_port, y = `s(Log_Min_dist_port)`, color = Position),
             data = myt_full, cex = 1, colour = "steelblue3") +
  geom_rug(aes(x = Log_Min_dist_port),
           data = myt_full,
           sides = "b", length = grid::unit(0.02, "npc")) +
  geom_ribbon(aes(ymin = .lower_ci, ymax = .upper_ci, x = Log_Min_dist_port),
              alpha = 0.2) +
    geom_line(aes(x = Log_Min_dist_port, y = .estimate), lwd = 1) +
  labs(y = "Partial effect", x = "Log Distance to the nearest port (km)") +
  geom_hline(yintercept = 0, linetype = 2) +
  theme_bw() 
    

Pl_fetch_smoother <-
  sm %>%
  filter(.smooth == "s(Log_Fetch)") %>%
  ggplot() +
  geom_point(aes(x = Log_Fetch, y = `s(Log_Fetch)`, color = Position),
             data = myt_full, cex = 1, colour = "steelblue3") +
  geom_rug(aes(x = Log_Fetch),
           data = myt_full,
           sides = "b", length = grid::unit(0.02, "npc")) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci, x = Log_Fetch),
              alpha = 0.2) +
    geom_line(aes(x = Log_Fetch, y = est), lwd = 1) +
  labs(y = "Partial effect", x = "Log Fetch (km)") +
  geom_hline(yintercept = 0, linetype = 2) +
  theme_bw()
  


##################################
#Predicted values in the terms of probabilities

# Pl_sal_smoother_Pi <-
#   sm %>%
#   filter(smooth == "s(Salinity)") %>%
#   ggplot() +
#   geom_point(aes(x = Salinity, y = Pi_Salinity), data = myt_full, cex = 1, colour = "steelblue3") +
#   geom_rug(aes(x = Salinity),data = myt_full, sides = "b", length = grid::unit(0.02, "npc")) +
#   geom_ribbon(aes(ymin = CI_Pi_low, ymax = CI_Pi_up, x = Salinity),alpha = 0.2) +
#   geom_line(aes(x = Salinity, y = Pi), lwd = 1) +
#   labs(y = "Partial effect", x = "Salinity (PPT)") +
#   # geom_hline(yintercept = median(myt_full$Pi_Salinity), linetype = 2)+
#   theme_bw()+
#   ylim(0, 0.8)
# 
# 
# Pl_riv_dist_smoother_Pi <-
#   sm %>%
#   filter(smooth == "s(Log_Min_dist_river)") %>%
#   ggplot() +
#   geom_point(aes(x = Log_Min_dist_river, y = Pi_Min_dist_river), data = myt_full, cex = 1, colour = "steelblue3") +
#   geom_rug(aes(x = Log_Min_dist_river),data = myt_full, sides = "b", length = grid::unit(0.02, "npc")) +
#   geom_ribbon(aes(ymin = CI_Pi_low, ymax = CI_Pi_up, x = Log_Min_dist_river),alpha = 0.2) +
#   geom_line(aes(x = Log_Min_dist_river, y = Pi), lwd = 1) +
#   labs(y = "Partial effect", x = "Distance to the nearest river (km)") +
#   # geom_hline(yintercept = median(myt_full$Pi_Min_dist_river), linetype = 2) +
#   theme_bw()+
#   ylim(0, 0.8)
# 
# 
# 
# Pl_port_dist_smoother_Pi <-
#   sm %>%
#   filter(smooth == "s(Min_dist_port)") %>%
#   ggplot() +
#   geom_point(aes(x = Min_dist_port, y = Pi_Min_dist_port), data = myt_full, cex = 1, colour = "steelblue3") +
#   geom_rug(aes(x = Min_dist_port),data = myt_full, sides = "b", length = grid::unit(0.02, "npc")) +
#   geom_ribbon(aes(ymin = CI_Pi_low, ymax = CI_Pi_up, x = Min_dist_port),alpha = 0.2) +
#   geom_line(aes(x = Min_dist_port, y = Pi), lwd = 1) +
#   labs(y = "Partial effect", x = "Log Distance to the nearest port (km)") +
#   # geom_hline(yintercept = median(myt_full$Pi_Min_dist_port), linetype = 2)+
#   theme_bw()+
#   ylim(0, 0.8)
# 
# 
# Pl_fetch_smoother_Pi <-
#   sm %>%
#   filter(smooth == "s(Fetch)") %>%
#   ggplot() +
#   geom_point(aes(x = Fetch, y = Pi_Average_Fetch), data = myt_full, cex = 1, colour = "steelblue3") +
#   geom_rug(aes(x = Fetch),data = myt_full, sides = "b", length = grid::unit(0.02, "npc")) +
#   geom_ribbon(aes(ymin = CI_Pi_low, ymax = CI_Pi_up, x = Fetch),alpha = 0.2) +
#   geom_line(aes(x = Fetch, y = Pi), lwd = 1) +
#   labs(y = "Partial effect", x = "Log Fetch (km)") +
#   # geom_hline(yintercept = median(myt_full$Pi_Average_Fetch), linetype = 2)+
#   theme_bw()+
#   ylim(0, 0.8)

```




```{r Parametric_prediction_figures}

# Predictions for parametric terms 

ds <-  data_slice(Mod_gam, Position = evenly(Position),  Port_Status = evenly(Port_Status), River_Size = evenly(River_Size)) 


Fit <- predict.gam(Mod_gam, newdata = ds, se = T, type = "link", exclude = c("s(Salinity)", "s(Log_Min_dist_river)",  "s(Log_Average_Fetch)",  "s(Log_Min_dist_port)", "s(Site)"))

ds$Fit = Fit$fit

ds$SE = Fit$se.fit
ds$CI_low <- (Fit$fit - 1.96*Fit$se.fit)
ds$CI_up <- (Fit$fit + 1.96*Fit$se.fit)




ds$Pi <- logit_back(Fit$fit)
ds$Pi_CI_low <- logit_back(Fit$fit - 1.96*Fit$se.fit)
ds$Pi_CI_up <- logit_back(Fit$fit + 1.96*Fit$se.fit)
#
#
Pl_Small <-
ds %>% filter(River_Size == "Small") %>%
ggplot(., aes(x = Position, y = Fit, fill = Port_Status)) +
  geom_col(position = position_dodge()) +
  scale_fill_manual(values = c("blue", "gray")) +
  geom_errorbar(aes(ymin = CI_low, ymax = CI_up), width = 0.2, position = position_dodge(width = 0.9)) +
  theme_bw()+
  ggtitle("The nearest River: Small") +
  theme(legend.position = c(0.8, 0.2)) +
  labs(x = "", y = "Partial effect", fill = "Nearest port status")
#
Pl_Large <-
ds %>% filter(River_Size == "Large") %>%
ggplot(., aes(x = Position, y = Fit, fill = Port_Status)) +
  geom_col(position = position_dodge()) +
  scale_fill_manual(values = c("blue", "gray")) +
  geom_errorbar(aes(ymin = CI_low, ymax = CI_up), width = 0.2, position = position_dodge(width = 0.9)) +
  theme_bw()+
  ggtitle("The nearest River: Large") +
  guides(fill = "none") +
  theme(legend.position = c(0.19, 0.5)) +
  labs(x = "", y = "Partial effect")
#





Pl_Small_Pi <-
ds %>% filter(River_Size == "Small") %>%
ggplot(., aes(x = Position, y = Pi, fill = Port_Status)) +
  geom_col(position = position_dodge()) +
  scale_fill_manual(values = c("blue", "gray")) +
  geom_errorbar(aes(ymin = Pi_CI_low, ymax = Pi_CI_up), width = 0.2, position = position_dodge(width = 0.9)) +
  theme_bw()+
  ggtitle("The nearest River: Small") +
  ylim(0, 0.8)+
  theme(legend.position = c(0.25, 0.8)) +
  labs(x = "", y = "Partial effect", fill = "Nearest port status") +
  geom_hline(yintercept = 0.5, color = "red")

#
Pl_Large_Pi <-
ds %>% filter(River_Size == "Large") %>%
ggplot(., aes(x = Position, y = Pi, fill = Port_Status)) +
  geom_col(position = position_dodge()) +
  scale_fill_manual(values = c("blue", "gray")) +
  geom_errorbar(aes(ymin = Pi_CI_low, ymax = Pi_CI_up), width = 0.2, position = position_dodge(width = 0.9)) +
  theme_bw()+
  ggtitle("The nearest River: Large") +
  ylim(0, 0.8)+
  guides(fill = "none") +
  theme(legend.position = c(0.19, 0.8)) +
  labs(x = "", y = "Partial effect")+
  geom_hline(yintercept = 0.5, color = "red")
    

# appraise(Mod_gam)

# tidy(Mod_gam, parametric = T)

```


```{r Models_summary}
sum_Model_1 <- summary(Mod_gam)

# sum_Model_2 <- summary(Mod_gam_reduced)

Mod_dummy <- lm(Prop_T ~ Salinity + Min_dist_river + Fetch + Min_dist_port + Position + River_Size + Port_Status,  data = myt_full )

library(car)

VIF <- vif(Mod_dummy) 

```




```{r Model1_output}
# Model 1 summary output preparation

Model_1_summ_smoothers <- tidy(Mod_gam)

Model_1_summ_smoothers$term <- c(
  "s(Salinity)", 
  "s(DistRiver)",
  "s(Fetch)",
  "s(DistPort)",
  "Random effect s(Site)")
Model_1_summ_smoothers[, 2:4] <- round(Model_1_summ_smoothers[, 2:4], 1)
Model_1_summ_smoothers[, 5] <- round(Model_1_summ_smoothers[, 5], 4)


Model_1_summ_parametric <- tidy(Mod_gam, parametric = T)

Model_1_summ_parametric$term <- c("(Intercept)",
                                  "Substrate(Algae)",
                                  "RiverSize(Large)",
                                  "PortStatus(Active)")
Model_1_summ_parametric[, 2:4] <- round(Model_1_summ_parametric[, 2:4], 1)
Model_1_summ_parametric[, 5] <- round(Model_1_summ_parametric[, 5], 4)

names(Model_1_summ_smoothers) <- names(Model_1_summ_parametric)


all_Model_1_summ <- rbind(Model_1_summ_smoothers, Model_1_summ_parametric)




ft_Model_1_summ_smoothers <- flextable(Model_1_summ_smoothers)

header <- c("Smoother terms", "edf", "ref.edf", "Chi.sq", "p-value")

ft_Model_1_summ_smoothers <- 
  ft_Model_1_summ_smoothers %>% 
  set_header_labels(values = header)






ft_Model_1_summ_parametric <- flextable(Model_1_summ_parametric)
header2 <- c("Parametric terms", "Parameter estimate", "SE", "z-statistic", "p-value")

ft_Model_1_summ_parametric <- 
  ft_Model_1_summ_parametric %>% 
  set_header_labels(values = header2)




```



```{r Model1_print_smoothers}
ft_Model_1_summ_smoothers <-
  ft_Model_1_summ_smoothers %>% 
  set_caption(caption = "Table 1 . Parameters of smoothers and coefficients of parametric terms for the Model describing dependency of Ptros on predictors.")

ft_Model_1_summ_smoothers %>% 
  width(j = 1:5, width = c(8, 4,2,2,2), unit = "cm")
```



```{r Model1_print_parametric}
# ft_Model_1_summ_parametric <-
  # ft_Model_1_summ_parametric %>% 
  # set_caption(caption = "Table + B. Parametric terms for the Model describing dependency of PT on predictors.")

ft_Model_1_summ_parametric %>%   
width(j = 1:5, width = c(8, 4,2,2,2), unit = "cm")
```





```{r Model1_prediction_Figure, fig.height= 8,fig.width=8, fig.cap= "Fig. 3. Predictions of the *Model 1* describing the dependency of *Ptros* on distance to the nearest port (A), average fetch (B), distance to the nearest river (C), salinity (E) and substrate type, nearest port status and size of the largest river (E, F). The  gray ribbons and wiskers demonstrate 95% confidence interval. The dotted lines in panels A-D represent the median predicted value, this value is given to track the trend in the change in model predictions. Points on panels A-D reflect partial residuals but not raw data for each sample."}

Pl_Model_1 <- 
  plot_grid(Pl_port_dist_smoother, Pl_fetch_smoother, Pl_riv_dist_smoother,  Pl_sal_smoother, Pl_Small_Pi, Pl_Large_Pi,  ncol = 2, labels = "AUTO")

Pl_Model_1

# ggsave(filename = "Fig_2.svg", plot = Pl_Model_1, width = 297,height = 210, units = "mm", dpi = 600)

```



```{r Salinity_discription_values }
# Different values needed for salinity effect discription

sal_smoother <- 
sm %>% 
  filter(smooth == "s(Salinity)")  

sm_low_salinity <- 
# sal_smoother %>% filter(est > median(est)) %>% filter(Salinity < 20) 
sal_smoother %>% filter(est > 0) %>% filter(Salinity < 20) 

  
Min_salinity <- round(max(sm_low_salinity$Salinity))

sm_high_salinity <- 
sal_smoother %>% filter(est > 0) %>% filter(Salinity > 20) 

Max_salinity <- round(min(sm_high_salinity$Salinity))


Number_sites_low_salinity <- myt_site %>% filter(Salinity <= round(Min_salinity, 0)) %>% nrow()

Number_sites_high_salinity <- myt_site %>% filter(Salinity >= round(Max_salinity, 0)) %>% nrow()

```



```{r Data_for_Substrate_modelling}

myt_sample_area <- read_excel("Data/myt_full.xls", sheet = "Sampling area assesment", na = "NA")

myt_sample_area <- myt_sample_area %>% dplyr::select(Site, Sample, Position, SQM_factor)


myt_full_reduced <- myt_full %>% filter(! Site %in% incomplete_sites)

myt_full_reduced <-
merge(myt_full_reduced, myt_sample_area)



myt_site_substr_reguced <- 
  myt_full_reduced %>% 
  mutate(D_T = N_T * SQM_factor, D_E = N_E*SQM_factor) %>% 
  group_by(Site, Position) %>% 
  summarise(D = mean(D_E + D_T), N_T = sum(N_T), N_E = sum(N_E),
        Salinity = mean(Salinity),
        Min_dist_river = mean(Min_dist_river),
        River_Size = unique(River_Size),
        Average_Fetch = mean(Average_Fetch),
        Min_dist_port = mean(Min_dist_port),
        Port_Status = unique(Port_Status),
        Lon = mean(Lon),
        Lat = mean(Lat), 
        D_T = mean(D_T),
        D_E = mean(D_E)) %>% 
  mutate(Prop_T = N_T/(N_T + N_E)) %>%
  mutate(Ptros = exp(-2.4 + 5.4 * Prop_T)/(1 + exp(-2.4 + 5.4 * Prop_T))) %>%
  mutate(Fi_T = 2*asin(sqrt(Prop_T))*180/pi)  




df1 <-
myt_site_substr_reguced %>% 
  dplyr::select(Site, Position, Ptros) %>%
  dcast(., formula = Site ~ Position, value.var = c("Ptros") ) 


names(df1) <- c("Site", "Ptros_Bottom", "Ptros_Algae" )
  

df2 <-
myt_site_substr_reguced %>% 
  dplyr::select(Site, Position, D) %>%
  dcast(., formula = Site ~ Position, value.var = c("D") )


names(df2) <- c("Site", "D_Bottom", "D_Algae" )

df3 <-
myt_site_substr_reguced %>% 
  dplyr::select(Site, Position, N_T, N_E) %>% 
  group_by(Site) %>% 
  summarise(N_T = sum(N_T), N_E = sum(N_E)) %>% 
  mutate(Total_Prop_T = N_T/(N_T + N_E)) %>% 
  mutate(Total_Ptros = exp(-2.4 + 5.4 * Total_Prop_T)/(1 + exp(-2.4 + 5.4 * Total_Prop_T))) %>%
  dplyr::select(-N_T, -N_E)


df4 <-
myt_site_substr_reguced %>% 
  group_by(Site) %>% 
  summarise(D_E = mean(D_E, na.rm = TRUE), D_T = mean(D_T, na.rm = TRUE))


df5 <-
myt_site_substr_reguced %>% 
  group_by(Site, Position) %>% 
  summarise(D_E = mean(D_E, na.rm = TRUE), D_T = mean(D_T, na.rm = TRUE)) %>%
  melt() %>% 
  dcast(., formula = Site ~ Position + variable)





```




```{r Model_Substrate_PT_Difference}

all_sites <- merge(df1, df2) %>% merge(., df3) %>% merge(., df4) %>% merge(., df5) %>%  
    mutate(Dif_Ptros = Ptros_Algae - Ptros_Bottom) %>% 
  mutate(D_mean = (D_Bottom + D_Algae)/2) %>% 
  mutate(Dif_D = log(D_Algae/D_Bottom)) %>% 
  mutate(D_total = D_T + D_E)

all_sites <- 
  all_sites %>%
  mutate(Log_D_total = log(D_total + 1),
         Log_Bottom_D_T = log(Bottom_D_T + 1),
         Log_Bottom_D_E = log(Bottom_D_E + 1),
         Log_Algae_D_T = log(Algae_D_T + 1),
         Log_Algae_D_E = log(Algae_D_E + 1),
         Log_D_T = log(D_T + 1),
         Log_D_E = log(D_E + 1)
         )

# qplot(y = all_sites$Dif_Ptros, x = all_sites$Total_Ptros) + geom_smooth()



all_sites <- 
  all_sites %>% 
  filter(complete.cases(.))

abundance <- 
  all_sites %>% 
  select(Log_Bottom_D_T, Log_Bottom_D_E, Log_Algae_D_T, Log_Algae_D_E)

# abundance <- 
#   all_sites %>% 
#   select(Bottom_D_T, Bottom_D_E, Algae_D_T, Algae_D_E)

library(vegan)

pca_abundance <- 
  rda(abundance)

# summary(pca_abundance)
# 
# plot(pca_abundance, type = "t", display = "species")

all_sites <-
  all_sites %>% 
  mutate(PC1 = scores(pca_abundance)$site[, 1], PC2 = scores(pca_abundance)$site[, 2])


#PC interpretation

# Pl_PC1_1 <- qplot(all_sites$PC1, all_sites$Log_Bottom_D_E) + labs(x = "", y = "Log(N)", title = paste("E-morphotype on Bottom, r = ", round(cor(all_sites$PC1, all_sites$Log_Bottom_D_E), 2)))
# 
# 
# Pl_PC1_2 <- qplot(all_sites$PC1, all_sites$Log_Algae_D_E) + labs(x = "", y = "Log(N)", title = paste("E-morphotype on Algae, r = ", round(cor(all_sites$PC1, all_sites$Log_Algae_D_E), 2)))
# 
# Pl_PC1_3 <- qplot(all_sites$PC1, all_sites$Log_Bottom_D_T) + labs(x = "", y = "Log(N) T on Bottom") + labs(x = "", y = "Log(N)", title = paste("T-morphotype on Bottom, r = ", round(cor(all_sites$PC1, all_sites$Log_Bottom_D_T), 2)))
# 
# 
# Pl_PC1_4 <- qplot(all_sites$PC1, all_sites$Log_Algae_D_T) + labs(x = "PC1", y = "Log(N) T on Algae") + labs(x = "PC 1", y = "Log(N)", title = paste("T-morphotype on Algae, r = ", round(cor(all_sites$PC1, all_sites$Log_Algae_D_T), 2)))
# 
# 
# 
# Pl_PC2_1 <- qplot(all_sites$PC2, all_sites$Log_Bottom_D_E)  + labs(x = "", y = "Log(N)", title = paste("E-morphotype on Bottom, r = ", round(cor(all_sites$PC2, all_sites$Log_Bottom_D_E), 2)))
# 
# 
# Pl_PC2_2 <- qplot(all_sites$PC2, all_sites$Log_Algae_D_E)  + labs(x = "", y = "Log(N)", title = paste("E-morphotype on Algae, r = ", round(cor(all_sites$PC2, all_sites$Log_Algae_D_E), 2)))
# 
# 
# Pl_PC2_3 <- qplot(all_sites$PC2, all_sites$Log_Bottom_D_T) + labs(x = "", y = "Log(N)", title = paste("T-morphotype on Bottom, r = ", round(cor(all_sites$PC2, all_sites$Log_Bottom_D_T), 2)))
# 
# 
# Pl_PC2_4 <- qplot(all_sites$PC2, all_sites$Log_Algae_D_T)  + labs(x = "", y = "Log(N)", title = paste("T-morphotype on Algae, r = ", round(cor(all_sites$PC2, all_sites$Log_Algae_D_T), 2)))
# 



Mod_Dif <- gam(Dif_Ptros ~ s(Total_Ptros) +  s(PC1) + s(PC2), method = "REML", data = all_sites)    


# foo_mod <- lm(Dif_Ptros ~ Total_Ptros + PC1 + PC2, data = all_sites)
# 
# vif(foo_mod)

# appraise(Mod_Dif)
# summary(Mod_Dif)

# draw(Mod_Dif, residuals = T)

# draw(Mod_Dif, residuals = TRUE)

summ_Mod_Dif <- tidy(Mod_Dif)


sm <- smooth_estimates(Mod_Dif) %>%
  add_confint() 

all_sites <-  add_residuals(data = all_sites,model = Mod_Dif, value = "Residuals")


Pl_Dif_model <- 
sm %>% 
  filter(smooth == "s(Total_Ptros)") %>% 
  ggplot(., aes(x = Total_Ptros, y = est)) +
  geom_line(color = "blue", linewidth = 1) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha=0.2 ) +
  # geom_hline(yintercept = median(sm$est), linetype = 2) +
  geom_point(data = all_sites, aes(y = Residuals),cex = 1, colour = "steelblue3") +
  labs(x = "Ptros in Site", y = "Partial effect")+
  geom_hline(yintercept = 0, linetype = 2)
 


library(ggtext)
library(glue)

#Correlations of PC1 with mussel abundance
df_PC1 <- data.frame(
  x = -0.7,
  y = -0.68,
  label = glue("**Correlation of PC1:** <br>E-morph on Bottom, r =  {round(cor(all_sites$PC1, all_sites$Log_Bottom_D_E), 2)} <br> E-morph on Algae,  r =  {round(cor(all_sites$PC1, all_sites$Log_Algae_D_E), 2)} <br> T-morph on Bottom,  r =  **{round(cor(all_sites$PC1, all_sites$Log_Bottom_D_T), 2)}** <br> T-morph on Algae,  r =  **{round(cor(all_sites$PC1, all_sites$Log_Algae_D_T), 2)}**"))


#The model for visualization of linear dependence of T-morphotype abundance on PC1 
Mod_D_T_PC1 <- lm(log(D_T + 1) ~ PC1, data = all_sites)
Pred_Mod_D_T_PC1 <- expand.grid(Part_eff = c(0.5, 0.55), PC1 = seq(min(all_sites$PC1), max (all_sites$PC1), length.out = 100))
Pred_Mod_D_T_PC1$Log_D_T_predicted = predict(Mod_D_T_PC1, newdata = Pred_Mod_D_T_PC1)
Pred_Mod_D_T_PC1$D_T_predicted <- exp(Pred_Mod_D_T_PC1$Log_D_T_predicted) - 1




Pl_Dif_model_PC1 <- 
sm %>% 
  filter(smooth == "s(PC1)") %>% 
  ggplot(., aes(x = PC1, y = est)) +
  geom_line(color = "blue", linewidth = 1) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha=0.2 ) +
  # geom_hline(yintercept = median(sm$est), linetype = 2) +
  geom_textbox(data = df_PC1, aes(x, y, label = label), width = grid::unit(0.7, "npc"), size = 2.3) +
  geom_point(data = all_sites, aes(y = Residuals),cex = 1, colour = "steelblue3") +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_tile(data = Pred_Mod_D_T_PC1, aes(x = PC1, y = Part_eff, fill = D_T_predicted)) + 
  scale_fill_gradient(low = "white", high = "red") +
  labs(x = "PC1", y = "Partial effect", fill = "T-morphotype \nabundance \n(ind./sq.m)") +
  theme(legend.position = "bottom")



df_PC2 <- data.frame(
  x = -0.55,
  y = -0.68,
  label = glue("**Correlation of PC2:** <br> E-morph on Bottom, r =  **{round(cor(all_sites$PC2, all_sites$Log_Bottom_D_E), 2)}** <br> E-morph on Algae,  r =  **{round(cor(all_sites$PC2, all_sites$Log_Algae_D_E), 2)}** <br> T-morph on Bottom,  r =  {round(cor(all_sites$PC2, all_sites$Log_Bottom_D_T), 2)} <br> T-morph on Algae,  r =  {round(cor(all_sites$PC2, all_sites$Log_Algae_D_T), 2)}"))



#The model for visualization of linear dependence of E-morphotype abundance on PC2 
Mod_D_E_PC2 <- lm(log(D_E + 1) ~ PC2, data = all_sites)
# summary(Mod_D_E_PC2)
Pred_Mod_D_E_PC2 <- expand.grid(Part_eff = c(0.5, 0.55), PC2 = seq(min(all_sites$PC2), max (all_sites$PC2), length.out = 100))
Pred_Mod_D_E_PC2$Log_D_E_predicted = predict(Mod_D_E_PC2, newdata = Pred_Mod_D_E_PC2)
Pred_Mod_D_E_PC2$D_E_predicted <- exp(Pred_Mod_D_E_PC2$Log_D_E_predicted) - 1

Pl_Dif_model_PC2 <- 
sm %>% 
  filter(smooth == "s(PC2)") %>% 
  ggplot(., aes(x = PC2, y = est)) +
  geom_line(color = "blue", linewidth = 1) +
  geom_ribbon(aes(ymin = lower_ci, ymax = upper_ci), alpha=0.2 ) +
  # geom_hline(yintercept = median(sm$est), linetype = 2)+
    geom_textbox(data = df_PC2, aes(x, y, label = label), width = grid::unit(0.7, "npc"), size = 2.3) +
  geom_point(data = all_sites, aes(y = Residuals),cex = 1, colour = "steelblue3") +
  geom_hline(yintercept = 0, linetype = 2) +
  geom_tile(data = Pred_Mod_D_E_PC2, aes(x = PC2, y = Part_eff, fill = D_E_predicted)) + 
  scale_fill_gradient(low = "white", high = "blue") +
  labs(x = "PC2", y = "Partial effect", fill = "E-morphotype \nabundance \n(ind./sq.m)") +
  theme(legend.position = "bottom")



# draw(Mod_Dif, residuals = TRUE)

```



# Supplementary electronic materials (SEM)

```{r Table_with_Ports_coordinates, eval=FALSE}

ports %>%
  select(-Shore) %>%
  kable(col.names = c("Port", "Status", "Latitude", "Longitude"), caption = "STable +. Ports presented in the Kandalaksha bay")
```

\pagebreak

### Associations between environmental parameters

Pearson correlation between environmental parameters
```{r Pearson_correlation_between_environmental_parameters}
# names(myt_site)
cor_df <-
myt_site %>% select(Salinity, Min_dist_river, Min_dist_port,Fetch) %>% as.data.frame(.) %>%  cor(., method = "pearson") %>% as.data.frame(.) %>% round(., 3) %>% mutate(Predictor = names(.))

cor_df <- cor_df[-4,]
cor_df[2:3, 1] <- NA
cor_df[3, 2] <- NA

cor_df <- cor_df %>% select(Predictor, Min_dist_river, Min_dist_port, Fetch)

ft_cor <- flextable(cor_df)

ft_cor

write.table(cor_df, "clipboard", sep = "\t", row.names = F)
# cor.test(myt_site$Min_dist_river, myt_site$Min_dist_port)
```

\pagebreak




```{r SFigure_preparation}
text_size <- 9

theme_set(theme_bw() + theme(panel.grid = element_blank(), axis.title = element_text(size = text_size), axis.text.x = element_text(size = text_size)))

port_neghbourds <- myt_site %>% group_by(Port) %>% summarise(Site_Number = n(), Median_Dist = median(Min_dist_port))

# range(round(port_neghbourds$Median_Dist))

Pl_Ports <-
  myt_site %>%
  ggplot(., aes(x = Port, y = Min_dist_port)) +
  geom_boxplot(fill = "gray80") +
  geom_text(data = port_neghbourds, aes(y = Median_Dist - 3, label = Site_Number)) +
  labs(x = "Ports", y = "Distance to the nearest port (km)") +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.6))



sites_fetch_df2 <-
  myt_full %>%
  select(Site, Site_Exposition, North_Fetch, East_Fetch, South_Fetch, West_Fetch, Average_Fetch) %>% 
  melt(., id.vars = c("Site", "Site_Exposition"), value.name = "Fetch", variable.name = "Direction")

sites_fetch_df2$Direction <- factor(sites_fetch_df2$Direction, labels = c("Nort", "East", "South", "West", "Average Fetch"))

# sites_fetch_df2 <- sites_fetch_df2 %>% filter(Direction == "Fetch")

Pl_Fetch <-
  ggplot(sites_fetch_df2, aes(x = Site_Exposition, y = Fetch)) +
  geom_boxplot() +
  # scale_fill_manual(values = c("gray95", "gray80", "gray70", "gray60", "gray40")) +
  labs(x = "Visual assessment of \nsite exposition", y = "Wind fetch (km)") +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.6))
# theme(legend.position = c(0.7, 0.75)) +



# range(myt_site$Salinity)

# median(myt_site$Salinity)


Pl_Salinity <-
  myt_full %>% group_by(Site, River_Size) %>%
  summarise(Salinity = mean(Salinity)) %>%
  ggplot(., aes(x = River_Size, y = Salinity)) +
  geom_violin(fill = "gray") +
  labs(x = "The size of the nearest river", y = "Salinity") +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.6))


Pl_Salinity_vs_Dist <-
  ggplot(myt_site, aes(x = Min_dist_river, y = Salinity)) +
  geom_point() +
  labs(x = "Distfnce to the nearest River", y = "Salinity")


Pl_Salinity_vs_Dist_to_Large_riv <-
  ggplot(myt_site, aes(x = Min_dist_river_Large, y = Salinity)) +
  geom_point() +
  labs(x = "Distfnce to the nearest Large River", y = "Salinity")


Pl_Fetch_vs_Dist_to_Port <-
  ggplot(myt_site, aes(x = Min_dist_port, y = Fetch)) +
  geom_point() +
  labs(x = "Distance to the nearest port", y = "Wind Fetch")


Pl_Salinity_vs_Dist_to_Port <-
  ggplot(myt_site, aes(x = Min_dist_port, y = Salinity)) +
  geom_point() +
  labs(x = "Distance to the nearest port", y = "Salinity")


```




```{r SFigure_Save, fig.width=8, fig.height=8, fig.cap="SFigure 1. Associations between environmental facters. "}

Pl_predictors <-
(Pl_Salinity_vs_Dist + Pl_Salinity) /
(Pl_Fetch_vs_Dist_to_Port + Pl_Salinity_vs_Dist_to_Port)  + plot_annotation(tag_levels = "A")

ggsave(plot = Pl_predictors, filename = "figures/Pl_predictors.svg", device = "svg", dpi = 600, width = 20, height = 20, units = "cm")


```



```{r SFigure_plot,  fig.cap= "SFigure +. Associations between environmental parameters used. (A) The association of salinity with distance to the mouth of the nearest river. (B) The kernel density violin-plots showing salinity variation for sites near Small and Large rivers. (C) The association between wind fetch and distance to the nearest port.  (D) The association of salinity with distance to the nearest port. ", fig.width=8, fig.height=8}

Pl_predictors
```



