---
title: "Structure, prevalence and morphotype"
author: 
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, cache = TRUE, warning = FALSE, message = FALSE)
library(knitr)

```

<style type="text/css">

body{ /* Normal  */
      font-size: 18px;
  }
td {  /* Table  */
  font-size: 20px;
}
h1.title {
  font-size: 38px;
  color: DarkRed;
}
h1 { /* Header 1 */
  font-size: 28px;
  color: DarkBlue;
}
h2 { /* Header 2 */
    font-size: 22px;
  color: DarkBlue;
}
h3 { /* Header 3 */
  font-size: 18px;
  font-family: "Times New Roman", Times, serif;
  color: DarkBlue;
}
code.r{ /* Code block */
    font-size: 12px;
}
pre { /* Code block - determines code spacing between lines */
    font-size: 14px;
}
</style>



```{r}
library(ggplot2)
library(reshape2)
library(dplyr)
library(doBy)
library(broom)
library(mgcv)


myt <- read.table("data_salinity3.csv", header = T, sep = ",")
# 
# myt_overseas <- myt[myt$dataset == "overseas", ]
# 
# myt <- myt[myt$dataset != "overseas", ]

# str(myt)

myt$Sp [myt$str > 0.5] <- "M.trossulus" #Лучше обозначать так!
myt$Sp [myt$str <= 0.5] <- "M.edulis"
myt$Sp <- factor(myt$Sp)


# Оставляем только мидий, у которых есть оценка морфотипа
myt2_all <- myt[!is.na(myt$ind), ]



### Объединяем популяции в данных Сары #####
# myt2_all$pop2 <- myt2_all$pop
# 
# myt2_all$pop[myt2_all$pop %in% c("CBCP", "CBSC")] <- "CB"
# 
# myt2_all$pop[myt2_all$pop %in% c("MDRE",   "MDRW")] <- "MDR"


# Подразделяем данные на сабсеты

myt2_all$Subset[myt2_all$sea == "barents" & myt2_all$sal_place == "fresh"] <- "WSBL" 
myt2_all$Subset[myt2_all$sea == "barents" & myt2_all$sal_place == "normal"] <- "BH" 
myt2_all$Subset[myt2_all$sea == "white" & myt2_all$sal_place == "normal"] <- "WSBL" 
myt2_all$Subset[myt2_all$sea == "white" & myt2_all$sal_place == "fresh"] <- "WSBL" 

myt2_all$Subset[myt2_all$sea == "Baltic"] <- "BALT" 
myt2_all$Subset[myt2_all$sea == "GOM"] <- "GOM" 
myt2_all$Subset[myt2_all$sea == "Norway"] <- "NORW" 
myt2_all$Subset[myt2_all$sea == "Scotland"] <- "SCOT" 


myt2_all$Subset <- factor(myt2_all$Subset, levels = c("WSBL", "BH",  "BALT", "GOM", "NORW", "SCOT" ))

# Вводим обозначения для морфотипов
myt2_all$morph <- ifelse(myt2_all$ind == 1, "T_m", "E_m")
myt2_all$morph <- factor(myt2_all$morph)



myt2 <- myt2_all %>% filter(Subset %in% c("WSBL", "BH", "BALT", "GOM" ))



# Бинарное обозначение видов

myt2$Sp2 <- ifelse(myt2$Sp == "M.trossulus", 1, 0)


#Correct identification
myt2$congr <- ifelse((myt2$ind == 1 & myt2$Sp == "M.trossulus") | (myt2$ind == 0 & myt2$Sp == "M.edulis"), 1, 0   )



# Частота M.trossulus в популяции, вычисленная как срденее значение structure

freq_MT <- summaryBy( str ~ pop, data = myt2)
names(freq_MT) <- c("pop", "freq_MT")

myt2 <- merge(myt2, freq_MT)

theme_set(theme_bw())

Pl_base <- ggplot(myt2, aes(x = freq_MT, y = str)) + scale_fill_gradient(low = "yellow", high = "red") + guides(fill = "none") + labs(x = "Prevalence (proportion of M.trossulus)", y = "Structure") + facet_wrap(~Subset) 

# + geom_density2d()


# Pl_base + geom_point(aes(fill = ind), shape = 21)

```

<!-- Для большей наглядности и избежания оверплоттинга точек добавим небольшой случайный разброс. -->

<!-- ```{r} -->
<!-- Pl_base + geom_point(aes(fill = ind), shape = 21, position = position_jitter(width = 0.01)) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- Pl_base + geom_point(aes(fill = ind), shape = 21, position = position_jitter(width = 0.01))  -->
<!-- ``` -->


$$
P_T = s[(Structure, Prevalence): Area] + Area + \varepsilon
$$



```{r echo = FALSE}
mod_gam <- gam(ind ~ s(str, freq_MT, by = Subset, bs = "tp", k = 10) + Subset, data = myt2, family = "binomial")

# summary(mod_gam)
```


```{r}

myt2_WSBL <- myt2 %>% filter(Subset == "WSBL")
myt2_BH <- myt2 %>% filter(Subset == "BH")
myt2_BALT <- myt2 %>% filter(Subset == "BALT")
myt2_GOM <- myt2 %>% filter(Subset == "GOM")



new_data_WSBL <-  myt2 %>% group_by(Subset) %>% do(expand.grid(str = seq(min(.$str), max(.$str), length.out = 20), freq_MT = seq(min(.$freq_MT), max(.$freq_MT), length.out = 20))) %>% filter(Subset == "WSBL") 

new_data_WSBL$Predict_gam <- predict(mod_gam, newdata = new_data_WSBL, type = "response" )

Pl_mod_gam_WSBL <-
  ggplot(new_data_WSBL, aes(x = freq_MT, y = str)) + 
  geom_raster(aes(fill = Predict_gam)) + 
  scale_fill_gradient(low = "cornflowerblue", high = "red") +
  theme_bw() + 
  labs(x = "", y = "", fill = "") +
  geom_density_2d(data = myt2_WSBL, color = "white")+
  theme(panel.grid = element_blank()) + 
  xlim(0,1)

Pl_mod_gam_WSBL <- Pl_mod_gam_WSBL + geom_point(data = myt2_WSBL,  position = position_jitter(width = 0.01), shape = 21, size = 1) 




new_data_BH <-  myt2 %>% group_by(Subset) %>% do(expand.grid(str = seq(min(.$str), max(.$str), length.out = 20), freq_MT = seq(min(.$freq_MT), max(.$freq_MT), length.out = 20))) %>% filter(Subset == "BH") 

new_data_BH$Predict_gam <- predict(mod_gam, newdata = new_data_BH, type = "response" )

Pl_mod_gam_BH <-
  ggplot(new_data_BH, aes(x = freq_MT, y = str)) + 
  geom_raster(aes(fill = Predict_gam)) + 
  scale_fill_gradient(low = "cornflowerblue", high = "red") +
  theme_bw() + 
  labs(x = "", y = "", fill = "") +
  geom_density_2d(data = myt2_BH, color = "white")+
  theme(panel.grid = element_blank()) + 
  xlim(0,1)

Pl_mod_gam_BH <- Pl_mod_gam_BH +  geom_point(data = myt2_BH, position = position_jitter(width = 0.01), shape = 21, size = 1) 



new_data_BALT <-  myt2 %>% group_by(Subset) %>% do(expand.grid(str = seq(min(.$str), max(.$str), length.out = 20), freq_MT = seq(min(.$freq_MT), max(.$freq_MT), length.out = 20))) %>% filter(Subset == "BALT") 

new_data_BALT$Predict_gam <- predict(mod_gam, newdata = new_data_BALT, type = "response" )

Pl_mod_gam_BALT <-
  ggplot(new_data_BALT, aes(x = freq_MT, y = str)) + 
  geom_raster(aes(fill = Predict_gam)) + 
  scale_fill_gradient(low = "cornflowerblue", high = "red") +
  theme_bw() + 
  labs(x = "", y = "", fill = "") +
  geom_density_2d(data = myt2_BALT, color = "white")+
  theme(panel.grid = element_blank()) + 
  xlim(0,1)

Pl_mod_gam_BALT <- Pl_mod_gam_BALT + geom_point(data = myt2_BALT, position = position_jitter(width = 0.01), shape = 21, size = 1) 



new_data_GOM <-  myt2 %>% group_by(Subset) %>% do(expand.grid(str = seq(min(.$str), max(.$str), length.out = 20), freq_MT = seq(min(.$freq_MT), max(.$freq_MT), length.out = 20))) %>% filter(Subset == "GOM") 

new_data_GOM$Predict_gam <- predict(mod_gam, newdata = new_data_GOM, type = "response" )

Pl_mod_gam_GOM <-
  ggplot(new_data_GOM, aes(x = freq_MT, y = str)) + 
  geom_raster(aes(fill = Predict_gam)) + 
  scale_fill_gradient(low = "cornflowerblue", high = "red") +
  theme_bw() + 
  labs(x = "", y = "", fill = "") +
  geom_density_2d(data = myt2_GOM, color = "white", n = 15)+
  theme(panel.grid = element_blank()) + 
  xlim(0,1)

Pl_mod_gam_GOM <- Pl_mod_gam_GOM + geom_point(data = myt2_GOM,  position = position_jitter(width = 0.01), shape = 21, size = 1) 


Pl_empty <- ggplot() + theme(panel.border = element_blank()) 




new_data <-  myt2 %>% group_by(Subset) %>% do(expand.grid(str = seq(min(.$str), max(.$str), length.out = 20), freq_MT = seq(min(.$freq_MT), max(.$freq_MT), length.out = 20)))


new_data$Predict_gam <- predict(mod_gam, newdata = new_data, type = "response" )

Pl_mod_gam <-
  ggplot(new_data, aes(x = freq_MT, y = str)) + 
  geom_raster(aes(fill = Predict_gam)) + 
  facet_wrap(~Subset, ncol = 1) + 
  scale_fill_gradient(low = "cornflowerblue", high = "red") +
  theme_bw() + 
  labs(x = "Prevalence (proportion of M.trossulus)", y = "Structure score", fill = "Probability of\nТ-morphotype \npresence") +
  geom_density_2d(data = myt2_WSBL, color = "white")+
  geom_density_2d(data = myt2_BH, color = "white")+
  geom_density_2d(data = myt2_BALT, color = "white")+
  geom_density_2d(data = myt2_GOM, color = "white", n = 5) +
  theme(panel.grid = element_blank())
# + 
#   geom_point(data = myt2, aes(fill = ind), position = position_jitter(width = 0.01), shape = 21, size = 1) 

  

library(ggpubr)

Pl_mod_gam_all <- ggarrange(Pl_mod_gam_WSBL, Pl_mod_gam_BH, Pl_mod_gam_BALT, Pl_mod_gam_GOM, ncol = 1)


  
```

```{r}

# prop_T <- myt2 %>%  mutate(str_class = ntile(str, 5)) %>% group_by(Subset, str_class) %>% summarise(str_mean = mean(str), Prop_T = mean(ind))



Pl_hist <- 
  ggplot(myt2_all, aes(x = str)) + 
  geom_histogram(binwidth = 0.1, color = "black", aes(fill = morph)) + 
  facet_wrap(~Subset, ncol = 1, scales = "free_y") + 
  scale_fill_manual(values = c("cornflowerblue", "red" )) + 
  theme_bw() +
  theme(panel.grid = element_blank()) + 
  guides(fill = "none") + 
  labs(x = "Structure score", y = "Count") + 
  coord_flip()
  
```



```{r  fig.height=9, fig.width=9}
library(cowplot)

plot_grid(Pl_hist, Pl_mod_gam, ncol = 2, labels = c("A", "B"), rel_heights = c(2,1))



  


```

