---
title: "Community changes modelling"
output:
  word_document:
    reference_docx: Report_structure.docx
    fig_width: 6
    fig_height: 5

---


```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, message = F, warning = F)

```



## Metrics of changes

The value of the above-described species as potential indicators is currently unknown. Some of them, probably, will poorly play this role due to natural temporal instability of their populations. That's why the optimal scheme of monitoring should be based on the regular (at least once per year) sampling at all or part of the stations where the abundance of one or another potential indicator is high enough.   

To reduce sampling effort only those stations that's common for several potential indicators should be sampled. After these stations would be sampled the mean abundance of species should be assessed. After this value  calculated it should be statistically compared with values presented above. As a simplest statistical test Student's t-test could be applied. 

We propose the scale of changes for each particular species summarized in the Table +. During the monitoring program it is highly recommended to store all sampled animals (alcohol fixation) with careful description of all sampling parameters (coordinates, dates, environmental parameters).

However it is necessary to note that information for all  species should be considered in combined way. It means that signals about changes in population of particular species should be combined with information about population of other species. For example  "Red" signal received for only one species it should be considered as more weak signal in comparison with situation when "red" signals were received for two or more species.       

\newpage

## Metrics of changes2

The value of the above-described species as potential indicators is currently unknown. Some of them, probably, will poorly play this role due to natural temporal instability of their populations. That's why the optimal scheme of monitoring should be based on the regular (at least once per year) sampling at all or part of the stations where the abundance of one or another potential indicator is high enough.   

To reduce sampling effort only those stations that's common for several potential indicators should be sampled. After these stations would be sampled the mean abundance of species should be assessed. After this value  calculated it should be statistically compared with values presented above. As a simplest statistical test Student's t-test could be applied. 

We propose the scale of changes for each particular species summarized in the Table +. During the monitoring program it is highly recommended to store all sampled animals (alcohol fixation) with careful description of all sampling parameters (coordinates, dates, environmental parameters).

However it is necessary to note that information for all  species should be considered in combined way. It means that signals about changes in population of particular species should be combined with information about population of other species. For example  "Red" signal received for only one species it should be considered as more weak signal in comparison with situation when "red" signals were received for two or more species.       

<div class="page"/>

## Metrics of changes3

The value of the above-described species as potential indicators is currently unknown. Some of them, probably, will poorly play this role due to natural temporal instability of their populations. That's why the optimal scheme of monitoring should be based on the regular (at least once per year) sampling at all or part of the stations where the abundance of one or another potential indicator is high enough.   

To reduce sampling effort only those stations that's common for several potential indicators should be sampled. After these stations would be sampled the mean abundance of species should be assessed. After this value  calculated it should be statistically compared with values presented above. As a simplest statistical test Student's t-test could be applied. 

We propose the scale of changes for each particular species summarized in the Table +. During the monitoring program it is highly recommended to store all sampled animals (alcohol fixation) with careful description of all sampling parameters (coordinates, dates, environmental parameters).

However it is necessary to note that information for all  species should be considered in combined way. It means that signals about changes in population of particular species should be combined with information about population of other species. For example  "Red" signal received for only one species it should be considered as more weak signal in comparison with situation when "red" signals were received for two or more species.       

#####

## Metrics of changes5

The value of the above-described species as potential indicators is currently unknown. Some of them, probably, will poorly play this role due to natural temporal instability of their populations. That's why the optimal scheme of monitoring should be based on the regular (at least once per year) sampling at all or part of the stations where the abundance of one or another potential indicator is high enough.   

To reduce sampling effort only those stations that's common for several potential indicators should be sampled. After these stations would be sampled the mean abundance of species should be assessed. After this value  calculated it should be statistically compared with values presented above. As a simplest statistical test Student's t-test could be applied. 

We propose the scale of changes for each particular species summarized in the Table +. During the monitoring program it is highly recommended to store all sampled animals (alcohol fixation) with careful description of all sampling parameters (coordinates, dates, environmental parameters).

However it is necessary to note that information for all  species should be considered in combined way. It means that signals about changes in population of particular species should be combined with information about population of other species. For example  "Red" signal received for only one species it should be considered as more weak signal in comparison with situation when "red" signals were received for two or more species.       

```{=openxml}
<w:p>
  </w:pPr>
    <w:r>
      <w:br w:type="page"/>
    </w:r>
</w:p>
```



## Metrics of changes6

The value of the above-described species as potential indicators is currently unknown. Some of them, probably, will poorly play this role due to natural temporal instability of their populations. That's why the optimal scheme of monitoring should be based on the regular (at least once per year) sampling at all or part of the stations where the abundance of one or another potential indicator is high enough.   

To reduce sampling effort only those stations that's common for several potential indicators should be sampled. After these stations would be sampled the mean abundance of species should be assessed. After this value  calculated it should be statistically compared with values presented above. As a simplest statistical test Student's t-test could be applied. 

We propose the scale of changes for each particular species summarized in the Table +. During the monitoring program it is highly recommended to store all sampled animals (alcohol fixation) with careful description of all sampling parameters (coordinates, dates, environmental parameters).

However it is necessary to note that information for all  species should be considered in combined way. It means that signals about changes in population of particular species should be combined with information about population of other species. For example  "Red" signal received for only one species it should be considered as more weak signal in comparison with situation when "red" signals were received for two or more species.       
