---
title: ""
author: "ВМ"
date: "29 12 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(readxl)
library(ggplot2)
library(dplyr)
library(nlme)
library(car)
library(lme4)
library(emmeans)

```



```{r}

byss_s <- read_excel('Data/Mytred_Byss_Salinity_2021.xlsx', sheet = 'list1')

# str(byss_s)

byss_ss <- select(byss_s, -Comment)
byss_ss$Force <- as.numeric(byss_ss$Force)
# str(byss_ss)
byss_ss <- na.omit(byss_ss)
# str(byss_ss)

byss_ss$Wtotal <- as.numeric(byss_ss$Wtotal)
byss_ss$Salinity <- as.numeric(byss_ss$Salinity)

# ggplot(data = byss_ss, aes(x = Salinity, y = Force, colour = Morph_type)) + geom_boxplot()  + scale_color_manual(values = c('blue' , 'red'))

byss_ss$Force_true <- byss_ss$Force - byss_ss$Wtotal/1000*9.8 

byss_ss$Force_true[byss_ss$Force_true<0] <- 0


```


```{r}

byss_ss$Salinity <- factor(byss_ss$Salinity)

byss_ss$LogForce <- log(byss_ss$Force_true + 1)

ppp_mod <- gls(data = byss_ss, LogForce ~ Salinity * Morph_type * Wtotal)

plot(ppp_mod)

ppp_mod2 <- gls(data = byss_ss, LogForce ~ Salinity * Morph_type * Wtotal, weights = varComb(varExp(form = ~Wtotal), varIdent(form=~1|Morph_type)))

ppp_mod3 <- gls(data = byss_ss, LogForce ~ Salinity * Morph_type * Wtotal, weights = varComb(varExp(form = ~Wtotal|Morph_type), varIdent(form=~1|Morph_type)))

AIC(ppp_mod, ppp_mod2, ppp_mod3)


plot(ppp_mod2)
```

```{r}
force_trends <- emtrends(ppp_mod2, specs = ~ Salinity * Morph_type, var= "Wtotal", mode = "df.error")


library(broom)

tidy(force_trends)

```




```{r}
library(effects)

my_data <- expand.grid(Morph_type = c("t", "e"), Wtotal = seq(from = min(byss_ss$Wtotal), to = max(byss_ss$Wtotal), length.out = 10))


Effects_salinity <- as.data.frame(allEffects(ppp_mod2, xlevels=my_data))

# Effects_salinity[[1]]

# Effects_salinity[[2]]


Pl_dif_sal <-
ggplot(Effects_salinity[[1]], aes(x = Wtotal, y = fit, group = Morph_type)) + 
  geom_line(aes(color = Morph_type)) +
  facet_wrap(~Salinity, nrow = 1) + 
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.2) + 
  scale_color_manual(values = c("blue", "red")) + 
  geom_point(data = byss_ss, aes(y = LogForce, color = Morph_type)) + ylab('Log(Сила прикрепления, Н)') + xlab('Масса мидии, г') + labs(color = 'Вид') + scale_x_continuous(breaks = c(12, 16, 20, 24)) + ylim(-0.1, 1.75)


```




```{r}
#Посмотрим контрольный эксперимент

byss_c <- read_excel('Data/Mytred_Byss_Control_2021.xlsx', sheet = 'list1')
# str(byss_c)
#View(byss_c)
byss_cc <- byss_c %>% filter(comment != 'Mistake')

# str(byss_cc)
byss_cc$Weight <- as.numeric(byss_cc$Weight)
byss_cc$Force <- as.numeric(byss_cc$Force)

byss_cc$Force_true <- byss_cc$Force - byss_cc$Weight/1000*9.8

byss_cc$Force_true[byss_cc$Force_true < 0] <- 0 

# which(byss_cc$Force_true > 2)

byss_cc$LogForce <- log(byss_cc$Force_true +1 )


# which(byss_cc$LogForce > 1.5)

 # byss_cc[19,]
 

byss_cc <- byss_cc %>% filter(byss_cc$LogForce < 1.5)
 
 
byss_cc <- byss_cc %>% filter(!is.na(LogForce))

byss_c_mod <- gls(data = byss_cc, LogForce ~ Morph_type * Weight)

plot(byss_c_mod)

byss_c_mod_2 <- gls(data = byss_cc, LogForce ~ Morph_type * Weight, weights = varComb(varExp(form = ~Weight), varIdent(form=~1|Morph_type)))

AIC(byss_c_mod, byss_c_mod_2)

plot(byss_c_mod_2, which = 1)
```


```{r}

my_data <- byss_cc %>% group_by(Morph_type) %>% do(data.frame(Weight = seq(min(.$Weight), max(.$Weight), length.out = 10)))

Effects_weight <- as.data.frame(allEffects(byss_c_mod_2, xlevels = my_data))


Pl_contr <- 
ggplot(Effects_weight[[1]], aes(x = Weight, y = fit, group = Morph_type)) + 
  geom_line(aes(color = Morph_type)) + 
  geom_ribbon(aes(ymin = lower, ymax = upper), alpha = 0.2) + 
  geom_point(data = byss_cc, aes(y = LogForce, color = Morph_type)) +scale_color_manual(values = c("blue", "red")) + ylab('Log(Сила прикрепления, Н)') + xlab('Масса мидии, г') + labs(color = 'Вид') +
   ylim(-0.1, 1.75)

```


```{r}
library(cowplot)
library(patchwork)

Pl_dif_sal + Pl_contr


```


## Связь силы прикрепления с соленостью


```{r}
emmeans_sal <- as.data.frame(emmeans(ppp_mod2, specs = ~Morph_type, by = "Salinity"))

ggplot(emmeans_sal, aes(x = Salinity, y = emmean)) + geom_col() + facet_wrap(~Morph_type)


ggplot(byss_ss, aes(x = Salinity, y = Force_true)) + geom_boxplot() + facet_wrap(~Morph_type)



```

