---
title: "Untitled"
author: ""
date: ""
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```



```{r}
library(mgcv)
library(ggplot2)
library(dplyr)
library(broom)
library(car)
library(reshape2)

options(knitr.kable.NA = '')




# Функция, задающая нумерацию рисунков

figRef <- local({
    tag <- numeric()
    created <- logical()
    used <- logical()
    function(label, caption, prefix = options("figcap.prefix"), 
        sep = options("figcap.sep"), prefix.highlight = options("figcap.prefix.highlight")) {
        i <- which(names(tag) == label)
        if (length(i) == 0) {
            i <- length(tag) + 1
            tag <<- c(tag, i)
            names(tag)[length(tag)] <<- label
            used <<- c(used, FALSE)
            names(used)[length(used)] <<- label
            created <<- c(created, FALSE)
            names(created)[length(created)] <<- label
        }
        if (!missing(caption)) {
            created[label] <<- TRUE
            paste0(prefix.highlight, prefix, " ", i, sep, prefix.highlight, 
                " ", caption)
        } else {
            used[label] <<- TRUE
            paste(prefix, tag[label])
        }
    }
})

options(figcap.prefix = "Рисунок", figcap.sep = ".", figcap.prefix.highlight = "**")



theme_set(theme_bw())

kam <- read.table("Data/kambala.csv", sep = ",", header = T, dec = ".")

# str(kam)
kam$Outcome <- ifelse(kam$Sidedness == "Left", 1, 0)



```









```{r}
library(mgcv)
library(ggplot2)
library(dplyr)
library(broom)
library(car)
library(cowplot)
library(readxl)


theme_set(theme_bw())

kam <- read.table("Data/kambala.csv", sep = ",", header = T, dec = ".")
kam$Orient <- kam$Sidedness
# str(kam)
kam$Outcome <- ifelse(kam$Orient == "Left", 1, 0)


```




```{r}
onega_cam_last <- read_excel("Data/Онежский залив без сомнительных данных.xlsx")

onega_cam_last <- onega_cam_last %>% filter(Sex != "j")


onega_new <- data.frame(Bay = "Onega_Bay", 
                        Sex = ifelse(onega_cam_last$Sex == "f", "Female", "Male"),
                        Sidedness = ifelse(onega_cam_last$Side == "l", "Left", "Right"),
                        L = onega_cam_last$L,
                        Orient = ifelse(onega_cam_last$Side == "l", "Left", "Right")
                        )
onega_new$Outcome <- ifelse(onega_new$Orient == "Left", 1, 0)


kam <- kam %>% filter(Bay != "Onega_Bay")

kam <- rbind(kam, onega_new)


# kam$Bay <- factor(kam$Bay, levels = c("Onega_Bay", "Dvina_Bay","Kandalaksha_Bay", "Mezen_Bay" ))

kam$Bay <- factor(kam$Bay, levels = c("Kandalaksha_Bay", "Onega_Bay", "Dvina_Bay", "Mezen_Bay" ), labels = c("Kandalaksha Bay", "Onega Bay", "Dvina Bay", "Mezen Bay" ))
```






```{r, fig.cap = figRef("Size_boxplot", "Характеристика размерного состава камбал в разных заливах Белого моря.") }



ggplot(kam, aes(x = Bay, y = L,  fill = Sidedness)) + geom_boxplot(notch = T) + facet_wrap(~Sex) + scale_fill_manual(values = c("gray10", "gray80")) + theme(panel.grid = element_blank(), axis.text.x = element_text(angle = 30, vjust = 0.6)) + labs(x = "Bay", y = "Length, cm", fill = "Morph")
```



```{r}

Mod <- glm(Outcome ~  L * Sex*Bay, data = kam, family = "binomial")
summary(Mod)
anova(Mod, test  = "Chi")
```



```{r, results='hide'}
drop1(Mod, test = "Chi")
Mod_2 <- update(Mod, . ~ . - L:Sex:Bay)

drop1(Mod_2, test = "Chi")
Mod_3 <- update(Mod_2, . ~ . - L:Sex)


drop1(Mod_3, test = "Chi")
Mod_4 <- update(Mod_3, . ~ . - L:Bay)

drop1(Mod_4, test = "Chi")
Mod_5 <- update(Mod_4, . ~ . - Sex:Bay)

drop1(Mod_5, test = "Chi")


Mod_6 <- update(Mod_5, . ~ . - L)

drop1(Mod_6, test = "Chi")

Mod_7 <- update(Mod_6, . ~ . - Sex)

AIC(Mod, Mod_7)


```



```{r}
AIC(Mod, Mod_6)

# kable(tidy(Mod_6))

```

```{r}
kable(tidy(Mod_6), caption = "Size Model parameters")
```



```{r fig.cap="**Fig.** Probability of left-sided morph in different bays, predicted by the regression Model 1. Fish size taken as mean for each bay separatelly, the value of mean size represented as number inside the columns. Wiskers represent 95% confidential interval."}

new_data <- kam %>% group_by(Bay) %>% do(data.frame(L = round(mean(.$L), 1)))

predicted <- predict(Mod_6, newdata = new_data, se.fit = T, type = "response")

new_data$Predicted <- predicted$fit
new_data$SE <- predicted$se.fit


ggplot(new_data, aes(x = Bay, y = Predicted)) + geom_col(fill = "gray", color = "gray10") + geom_errorbar(aes(ymin = Predicted - 1.96*SE, ymax = Predicted + 1.96*SE), width = 0.1) + geom_text(aes(y = Predicted - 1.96*SE -0.01, label = L)) + labs(y = "Probability of left-sided morph")


```




```{r }

new_data <- kam %>% group_by(Bay) %>% do(data.frame(L = seq(min(.$L), max(.$L), length.out = 100) )) %>% filter(Bay == "Onega_Bay")

predicted <- predict(Mod_6, newdata = new_data, se.fit = T, type = "response")

new_data$Predicted <- predicted$fit
new_data$SE <- predicted$se.fit

Left_prop <- kam %>% group_by(Bay) %>% do(data.frame(L = .$L, Orient = .$Orient, Size_class = cut_number(x = .$L, n = 25))) %>% group_by(Bay,Size_class) %>% summarise(L_mean = mean(L), Left_prop = mean(Orient == "Left"), N = n()) %>% filter(N>0)  %>% filter(Bay == "Onega_Bay")


  
  


kam_oneg <- kam %>% filter(Bay == "Onega_Bay")

Pl_size_onega <-
ggplot(new_data, aes(x = L, y = Predicted)) + 
  geom_line( size = 1) +  
  geom_ribbon(aes(ymin = Predicted - 1.96*SE, ymax = Predicted + 1.96*SE), alpha = 0.5 ) + 
  geom_point(data = Left_prop, aes(x = L_mean, y = Left_prop), shape = 21, size = 2, fill = "gray") + 
  facet_wrap(~ Bay, ncol = 2) +
  labs(x = "Length, cm", y = "Frequency of left-sided morph") +
  geom_segment(data = kam_oneg, aes(x = L, xend = L, y = 0, yend = 0.01)) +
  theme(strip.text = element_blank())



```








```{r}
onega_cam_last <- read_excel("Data/Онежский залив без сомнительных данных.xlsx")

onega_cam_previous <- read_excel("Data/Onega_L_Age.xlsx")

# hist(onega_cam_last$L)
# hist(onega_cam_previous$L)
# 
# hist(onega_cam_last$Age)
# hist(onega_cam_previous$Age)
# 
# 
# 
# 
# df1 <- onega_cam_last %>% group_by(Sex, Age) %>% summarise(n = n(), Side = mean(Side == "l"))
# 
# df2 <- onega_cam_previous %>% group_by(Sex, Age) %>% summarise(n = n(), Side = mean(Side == "l"))
# 
# sum(onega_cam_last$Side == "l") 
# 
# sum(onega_cam_previous$Side == "l")
# 
# 
# cbind(df1, df2)
# 
# 
# plot(df1$n, df2$n)
# 
# plot(df1$Side, df2$Side)
# 



onega_cam <- onega_cam_last

onega_cam <- onega_cam %>% filter(Sex !="j")

onega_cam$Side2 <- ifelse(onega_cam$Side == "l", 1, 0)






# onega_cam2 <- onega_cam[-c(2353:2356),]

# onega_cam3 <- onega_cam2 %>% filter(Age<=7)


# onega_cam3 <- onega_cam %>% filter(Age<=7 & Age > 1)

onega_cam3 <- onega_cam %>% filter(Age > 1) 

# nrow(onega_cam3)/nrow(onega_cam2)
# max(onega_cam2$Age)

# str(onega_cam3$Sex)

onega_cam3$Sex <- factor(onega_cam3$Sex)

onega_cam3$Sex <-factor(onega_cam3$Sex, labels = c("female", "male"))


M <- glm(Side2 ~ Age + Sex , data = onega_cam3, family = "binomial")


# cam_oneg <- kam %>% filter(Bay == "Kandalaksha_Bay")
# 
# M2 <- glm(Outcome ~ L, data = cam_oneg, family = "binomial")


# summary(M)
# summary(M2)

# nrow(onega_cam3)

# max(onega_cam3$Age)

```





```{r}
kable(tidy(M), caption = "Age Model parameters")


```


```{r}

mydata <- onega_cam3 %>% group_by(Sex) %>% do(data.frame(Age = seq(min(.$Age), max(.$Age), length.out = 50)))


fit <- predict(M, newdata = mydata, type = "response", se.fit = T)

mydata$fit <- fit$fit

mydata$SE <- fit$se.fit

P_age <- onega_cam3 %>% group_by(Sex, Age) %>% summarize(P_left = mean(Side2 == 1), N = n())

Pl_age_onega <- 
ggplot(mydata, aes(x = Age, y = fit, linetype = Sex))  + 
  geom_ribbon(aes(ymin = fit - 1.96*SE, ymax = fit + 1.96*SE), alpha = 0.3) + 
  geom_line(size = 1) +
  geom_point(data = P_age, aes(x = Age, y = P_left, fill = Sex), size = 4, shape = 21, color = "black") +
  scale_fill_manual(values = c("white", "black") ) +
  theme_bw() +
  labs(y = "Frequency of left-sided morph", x = "Age, years", fill = "", linetype = "") +
  theme(legend.position = "bottom") +
  guides(shape = guide_legend(override.aes = list(fill = 20)))

```


```{r fig.cap="**Fig.** Association between probability of left-sided morph and fish length (A) and age (B). Points represent frequency of reversed fish in 25 length classes of equal sample size. Gray area around regression line represent 95% confidential interval."}


plot_grid(Pl_size_onega, Pl_age_onega, ncol = 1, labels = c("A", "B"), hjust = c(-5, -5) )

```



