---
title: ""
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```

```{r}
library(mgcv)
library(ggplot2)
library(dplyr)
library(broom)
library(car)
library(reshape2)

options(knitr.kable.NA = '')




# Функция, задающая нумерацию рисунков

figRef <- local({
    tag <- numeric()
    created <- logical()
    used <- logical()
    function(label, caption, prefix = options("figcap.prefix"), 
        sep = options("figcap.sep"), prefix.highlight = options("figcap.prefix.highlight")) {
        i <- which(names(tag) == label)
        if (length(i) == 0) {
            i <- length(tag) + 1
            tag <<- c(tag, i)
            names(tag)[length(tag)] <<- label
            used <<- c(used, FALSE)
            names(used)[length(used)] <<- label
            created <<- c(created, FALSE)
            names(created)[length(created)] <<- label
        }
        if (!missing(caption)) {
            created[label] <<- TRUE
            paste0(prefix.highlight, prefix, " ", i, sep, prefix.highlight, 
                " ", caption)
        } else {
            used[label] <<- TRUE
            paste(prefix, tag[label])
        }
    }
})

options(figcap.prefix = "Рисунок", figcap.sep = ".", figcap.prefix.highlight = "**")



theme_set(theme_bw())

age_all <- read.table("Data/age_Onega.csv", sep = ",", header = T, dec = ".")

age <- age_all %>% filter(Age %in% 2:7)

# age_old <- age_all %>% filter(Age > 7)
# 
# age_old <- age_old %>% group_by(Sex) %>% filter(Right + Left >0) %>% summarise(Age = mean(Age), Right = sum(Right), Left  = sum(Left))
# 
# age <- rbind(age, age_old)

```




## Частота реверсивных особей в разных географических областях 

```{r}
library(ggmap)
library(mapproj)
library(maps)

library(rgeos) #этот пакет содержит какую-то хрень, которая позволяет обойти проблему пр чтении фалов средсвами maptools. 
#Att! Этот пакет должен быть загружен до maptools

library(mapdata)
library(maptools) # Rgshhs
library(PBSmapping)
library(gridExtra)
library(grid)
library(ggrepel)


theme_set(theme_bw() + theme(legend.key = element_blank()))

df_europ <- read.csv("Data/Europe_polygon.csv", header = T)


# Задаем пределы координат

Full_x <- c(-10, 50)
Full_y <- c(49, 72)

gg_full <- ggplot(df_europ, aes(x=long, y=lat, group=group)) +
  geom_polygon(fill = "gray95", colour = "gray60") + 
  coord_map(xlim = Full_x, ylim = Full_y) + 
  theme_bw() +  
  theme(axis.title.x =element_blank(),  axis.title.y= element_blank(), plot.background = element_rect(fill = "white"), panel.grid = element_blank()) + 
  theme(axis.text.x =element_blank(), axis.text.y= element_blank()) + 
  theme(axis.ticks = element_blank()) 


```




```{r,  fig.cap= figRef("Left_map", "Частота реверсивных особей в разных частях ареала. Размер точки пропорционален частоте."), fig.height=5}

left_prop <- read.csv("Data/point_proportion.csv", header = T)
point_coord <- read.csv("Data/point_coordinates.csv", header = T)
point_n <- read.csv("Data/point_sample_size.csv", header = T)



point_coord$Lat <- point_coord$Lat + point_coord$Lat_m / 60 
point_coord$Long <- point_coord$Long + point_coord$Long_m / 60

points <- data.frame(Point = 1:nrow(left_prop), left_prop, Lat = point_coord$Lat, Long = point_coord$Long)

Pl_revers <-
  gg_full + 
  geom_point(data = points, aes(x = Long, y = Lat, size = Left_prop, group = 1, fill = Left_prop), shape = 21) + 
  scale_size_continuous(breaks = seq(0, 50, 5)) + 
  scale_fill_gradient(low = "yellow", high = "red")+
  geom_text_repel(data = points, aes(x = Long, y = Lat, group = 1, label = 1:nrow(points)), force = 3, box.padding = 0.5) + 
  labs(size = "Proportion of Reverse", fill = "Доля реверсивных рыб, %") +
  theme(legend.position = "bottom") +
  guides(size = "none")

 ggsave(plot = Pl_revers, filename = "Map_of_reverse_distribution.pdf")  

Pl_revers

```

<br>
<br>

```{r}
points_print <- points[ ,1:4]
points_print <- cbind(points_print, point_n) 

points_print$Left_Right <- paste(points_print$Left, "/", 100-points_print$Left, sep = "")

points_print<- cbind(points_print, point_coord)

points_print$Point_number <- 1:nrow(points_print)

points_print <- points_print %>% select(Point_number, Site, n, Left_Right,  Lat, Long, Source ) 


kable(points_print, caption = "**Таблица +**. Доля (%) реверсивных рыб в разных участках ареала.", col.names = c("№", "Site", "Sample Size", "Proportion Left/Right ", "Lat", "Long", "Source") )
```

