---
title: "Untitled"
author: "ВМ"
date: "23 10 2020"
output: html_document
---

```{r}
library(ggplot2)

library(ggmap)
library(mapproj)
library(maps)

library(rgeos) #этот пакет содержит какую-то хрень, которая позволяет обойти проблему пр чтении фалов средсвами maptools. 
#Att! Этот пакет должен быть загружен до maptools

library(mapdata)
library(maptools) # Rgshhs
library(PBSmapping)
library(gridExtra)
library(grid)


theme_set(theme_bw() + theme(legend.key = element_blank()))
# Задаем пределы координат

Full_x <- c(-10, 50)
Full_y <- c(45, 72)



gshhs.l.b <- "d:/Data_LMBE/Maps/Gshhs/gshhs_l.b"

gshhs.f.b <- "d:/Data_LMBE/Maps/Gshhs/gshhs_f.b"
wdb_rivers.f.b <- "d:/Data_LMBE/Maps/Gshhs/wdb_rivers_f.b"
wdb_borders.f.b <- "d:/Data_LMBE/Maps/Gshhs/wdb_borders_f.b"




Kl <- getRgshhsMap(fn = gshhs.l.b, xlim = Full_x, ylim = Full_y)

Kf <- getRgshhsMap(fn = gshhs.f.b, xlim = Small_x, ylim = Small_y)

dfKl <- fortify(Kl)
dfKf <- fortify(Kf)

gg_full <- ggplot(dfKl, aes(x=long, y=lat, group=group)) +
  geom_polygon(fill = "gray90", colour = "gray20") + coord_map(xlim = Full_x, ylim = Full_y) + theme_bw() +  theme(axis.title.x =element_blank(),  axis.title.y= element_blank(), plot.background = element_rect(fill = "white"), panel.grid = element_blank()) + theme(axis.text.x =element_blank(), axis.text.y= element_blank()) + theme(axis.ticks = element_blank()) 


```




```{r}
left_prop <- read.csv("Data/point_proportion.csv", header = T)
point_coord <- read.csv("Data/point_coordinates.csv", header = T)

point_coord$Lat <- point_coord$Lat + point_coord$Lat_m / 60 
point_coord$Long <- point_coord$Long + point_coord$Long_m / 60

points <- data.frame(left_prop, Lat = point_coord$Lat, Long = point_coord$Long)

gg_full + geom_point(data = points, aes(x = Long, y = Lat, size = Left_prop, group = 1), shape = 21, fill = "blue")+ scale_size_continuous(breaks = seq(0, 50, 5))



ggplot(points, aes(x = Long, y = Left_prop)) + geom_point()  + geom_smooth() 

ggplot(points[points$Lat >65, ], aes(x = Lat, y = Left_prop)) + geom_point() + geom_smooth(method= "lm")


```

