---
title: ''
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r}
library(ggplot2)
library(readxl)
library(dplyr)
library(broom)



onega_cam <- read_excel("Data/Onega_L_Age.xlsx")

onega_cam <- onega_cam %>% filter(Sex !="j")

onega_cam$Side2 <- ifelse(onega_cam$Side == "l", 1, 0)



onega_cam2 <- onega_cam[-c(2353:2356),]



onega_cam3 <- onega_cam2 %>% filter(Age<=7)



M <- glm(Side2 ~ Age * Sex, data = onega_cam3, family = "binomial")

```



```{r}
kable(tidy(M), caption = "Model parameters")
```



```{r}
kable(tidy(anova(M, test = "Chi")), caption = "Analysis of deviannce")

```


```{r}

mydata <- onega_cam3 %>% group_by(Sex) %>% do(data.frame(Age = seq(min(.$Age), max(.$Age), length.out = 50)))


fit <- predict(M, newdata = mydata, type = "response", se.fit = T)

mydata$fit <- fit$fit

mydata$SE <- fit$se.fit

P_age <- onega_cam3 %>% group_by(Sex, Age) %>% summarize(P_left = mean(Side2 == 1), N = n())


ggplot(mydata, aes(x = Age, y = fit, color = Sex))  + 
  geom_ribbon(aes(ymin = fit - 1.96*SE, ymax = fit + 1.96*SE), alpha = 0.3) + 
  geom_line(size = 1) +
  geom_point(data = P_age, aes(x = Age, y = P_left, color = Sex), size = 4) +
  theme_bw() +
  labs(y = "Probability of left")

```

