---
output: word_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
                      
```


```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)
library(reshape2)
library(vegan)
library(mgcv)
library(ggrepel)
library(broom)
library(tidyr)

cam <- read_excel("Data/All_length_age_year.xlsx") 

cam$Orient2 <- ifelse(cam$Orient == "Left", 1, 0)
```


```{r}
cam$Bay <- factor(cam$Bay)

# Mod2 <- gam(Orient2 ~ s(Year, by = Bay) +  Bay, data = cam, family = "binomial")

Mod2 <- glm(Orient2 ~ Year*Bay, data = cam, family = "binomial")

# drop1(Mod2, test = "Chi")

Mod3 <- glm(Orient2 ~ Year + Bay, data = cam, family = "binomial")



Mod_Dvina <- glm(Orient2 ~ Year, data = cam[cam$Bay == "Dvina", ], family = "binomial")
summary(Mod_Dvina)

Mod_Onega <- glm(Orient2 ~ Year, data = cam[cam$Bay == "Onega", ], family = "binomial")
summary(Mod_Onega)


Mod_Mezen <- glm(Orient2 ~ Year, data = cam[cam$Bay == "Mezen", ], family = "binomial")
summary(Mod_Mezen)



# summary(Mod2)

mydata <- cam %>% group_by(Bay) %>% do(data.frame(Year = seq(min(.$Year), max(.$Year), 1)))


predicted <- predict(Mod3, newdata = mydata, se.fit = T, type = "response")


mydata$Fit = predicted$fit

mydata$SE = predicted$se.fit


left_freq <- cam %>%  group_by(Bay, Year) %>% summarise(Left_prop = mean(Orient2))

historic_data <- data.frame(Bay = c("Onega", "Onega", "Dvina", "Кandalaksha", "Кandalaksha"), Year = c(1950, 1948, 2005, 1962, 2006), Left_prop = c(0.285, 0.313, 0.04, 0.38, 0.36), N = c(358, 182, 897, 507, 450), Source = c(1, 2, 3, 4, 5), shift = c(1.5, rep(-1.5, 4)) )

historic_data$SE <- with(historic_data, sqrt(Left_prop*(1-Left_prop)/N)  ) 


ggplot(mydata, aes(x = Year, y = Fit, group = Bay)) + geom_line(aes(linetype = Bay), size = 1) + 
    geom_ribbon(aes(ymax = Fit + 1.96*SE, ymin = Fit - 1.96*SE), alpha = 0.2) + 
  geom_point(data = left_freq, aes(y = Left_prop, shape = Bay), size = 3, fill = "gray")  + 
  geom_errorbar(data = historic_data, aes(x = Year, y = Left_prop,   ymin = Left_prop - 1.96 * SE, ymax = Left_prop + 1.96 * SE), width = 0.5) + 
  geom_point(data = historic_data, aes(x = Year, y = Left_prop,  shape = Bay), size = 6, fill = "white")+ 
  geom_text(data = historic_data, aes(x = Year + shift, y = Left_prop, label = Source)) +
  labs(x = "Year",  y = "Proportion of left-sided morph", shape = "Bay:") + 
  theme_bw() + 
  scale_shape_manual(values = c(15, 17, 16, 18)) +
  guides(linetype = "none") +
  theme(legend.position = "bottom")

  


```

```{r}
mod_summary <- tidy(Mod3)

mod_summary[,2:4] <- round (mod_summary[,2:4], 4)

mod_summary[,5] <- round (mod_summary[,5], 4)


kable(mod_summary, col.names = c("Model term", "Parameter", "SE", "Z-statistic", "p-value"), caption = "Table ++. Parameters of model fitted")
```



