---
title: ""
author: "В. М. Хайтов"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)

opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

```



```{r}
library(ggmap)
library(mapproj)
library(maps)
library(rgeos) #этот пакет содержит какую-то хрень, которая позволяет обойти проблему пр чтении фалов средствами maptools. 
#Att! Этот пакет должен быть загружен до maptools
library(mapdata)
library(maptools) # Rgshhs
library(PBSmapping)
library(sf)


library(readxl)
library(dplyr)
library(cowplot)
library(png)
library(reshape2)
library(tibble)

library(mgcv)
library(vegan)

```


```{r}
biomass <- read_excel("Data/Finnish_gulf_working_data.xlsx", sheet = "Biomass_working") 

biomass <- 
  biomass %>%
  `row.names<-`(., NULL) %>% 
  column_to_rownames(var = "sampling_station_name")

abund <- read_excel("Data/Finnish_gulf_working_data.xlsx", sheet = "Abundance_working")
abund <- 
  abund %>%
  `row.names<-`(., NULL) %>% 
  column_to_rownames(var = "sampling_station_name")
```

```{r}
taxonomy <- read_excel("Data/Finnish_gulf_working_data.xlsx", sheet = "Species Taxonomy")
```




```{r}

Fin_df <- read.csv("Data/Finnish_Gulf_East.csv") # Map poligones

# Basic map layer####################

theme_set(theme_bw())



Pl_Finnish_Gulf <- 
  ggplot(Fin_df, aes(x=long, y=lat, group=group)) +
  geom_polygon(fill = "gray90", colour = "gray20") + 
  theme(axis.title.x = element_blank(),  axis.title.y = element_blank(), plot.background = element_blank(), panel.border = element_blank(), panel.grid = element_blank()) + 
  theme(axis.text.x =element_blank(), axis.text.y= element_blank()) + 
  theme(axis.ticks = element_blank())


```

```{r}

# Data reading
stations <- read_excel("Data/Finnish_gulf_working_data.xlsx", sheet = "Station parameters")

stations <- stations %>% filter(long >= 27.054848)

points <- stations %>% select(sampling_station_name,lat, long) %>% filter(long >= 27.054848)


```

## Отбор станций


```{r }

work_area <- read_sf(dsn = "Data/Work polygon.kml")

```



```{r}
points_sf <- st_as_sf(points, coords = c("long", "lat"), crs = 4326 )
load("Data/Finnish_gulf_East.RData")

point_in_pol <- as.numeric(st_within(points_sf, map))

stations_on_land <- points %>% filter(point_in_pol == 1)

# load("Data/Finnish_gulf.RData")

point_in_pol <- as.numeric(st_within(points_sf, map))
```

```{r}

stations_on_land <- points %>% filter(point_in_pol == 1)

stations_on_land_print <- stations_on_land %>%  select(sampling_station_name, lat, long) %>% as.data.frame()
```


```{r fig.cap="**Рисунок. ** Расположение станций, вовлеченных в анализ пространственного варьирования интегральных показателей. Синяя линия ограничивает область, на которой будет проводиться экстарполяция предсказаний модели, описывающей постранственное варьирование интегральных показателей "}

work_polygon_sf <- st_as_sf(work_area, coords = c("long","lat"), crs = 4326)

points_in_work_polygon <- points %>% filter(as.numeric(st_within(points_sf, work_polygon_sf)) == 1) 

work_polygon_coordinates <- as.data.frame(st_coordinates(work_polygon_sf)) %>% select(1, 2)

names(work_polygon_coordinates) <- c("long", "lat")  
  
 ggplot(data = points, aes(x = long, y = lat)) + 
   geom_point(size = 0.1) + 
   geom_polygon(data = work_polygon_coordinates, aes(group = 1), fill = NA, color = "blue" )+
   geom_polygon(data = Fin_df, aes(group = group), fill = "gray90", colour = "gray20")
   
   

```


Станции за пределами основного полигона

```{r}
st <- stations %>% filter(! sampling_station_name %in% points_in_work_polygon$sampling_station_name) %>% select(sampling_station_name) %>% pull() 


paste(st, sep = ", ")

```

