---
title: "Донные сообщества Южной части Финского залива"
subtitle: "Анализ на основе базы данных"
author: 
  - Марина Ивановна Орлова
  - Валентина Сергеевна Котельникова
  - Вадим Михайлович Хайтов
company: 'СПбНЦ'
output:
  xaringan::moon_reader:
    self-contained: true
    lib_dir: libs
    css: [default, tamu-fonts, ninjutsu, "assets/xaringan-themer.css", "assets/xaringan.css"]
    df_print: default
    nature:
      highlightStyle: vs
      highlightLines: true
      countIncrementalSlides: false
      titleSlideClass: [middle, left, inverse]
      beforeInit: "assets/macros.js"
    includes:
      in_header: "assets/xaringan_in_header.html"
      after_body: "assets/xaringan_after_body.html"
---



```{r setup, include = FALSE, cache = FALSE, purl = FALSE}
# output options
options(width = 70, scipen = 6, digits = 3)
library(knitr)
library(ggplot2)
library(grid)
library(gridExtra)


# chunk default options
opts_chunk$set(fig.align='center', tidy = FALSE, warning = FALSE, echo = FALSE, message = FALSE)

ar <- arrow(type = "closed", length = unit(0.15,"cm"))
```


```{r}
invaders <- c("Dreissena polymorpha", "Potamopyrgus antipodarum","Amphibalanus improvisus", "Gammarus tigrinus")

```

---

class: small
## Выбор видов

К числу инвазивных видов были отнесены следующие формы, рассмотренные  в монографии "Самые опасные инвазионные виды России (ТОП-100)": `r paste(invaders, collapse=", ")`. 
