---
title: "Сообщества гидробионтов Обской губы"
author: "Вадим Хайтов"
date: "30 01 2021"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(echo = FALSE)
```

В настоящий аналииз основан на том материале, который есть (использованы данные со станций О1-О45). 

Остро не хватает 

1. Географических координат станций.   
2. Цифровых данных по солености (видимо, взятых из модели, результаты которой пока есть только в виде картинок).   
3. Любых других данных по абиотическим параметрам, привязанным к станциям. 





```{r}
library(readxl)
library(vegan)
library(dplyr)
library(ggvegan)


# Read data

bent <- read_excel("Data/Obskaya_bay.xlsx", sheet = "Benthos", col_types = "guess")

planct <- read_excel("Data/Obskaya_bay.xlsx", sheet = "Plancton", col_types = "guess", na = "NA")

phyt_planct <- read_excel("Data/Obskaya_bay.xlsx", sheet = "Phytoplancton abundance", col_types = "guess")


phyt_planct_present <- read_excel("Data/Obskaya_bay.xlsx", sheet = "Phytoplancton species presence", col_types = "guess")

phyt_planct_present[is.na(phyt_planct_present)] <- 0


env <-  read_excel("Data/Obskaya_bay.xlsx", sheet = "Environment", col_types = "guess")

```



## Бентосные сообщества

```{r}

phyt_planct_station <-  phyt_planct %>% filter(Type == "Abundance") %>%  group_by(Station) %>% summarise_all(mean) %>% select(-c(Horizont,  Type))


predictors <- merge(env %>% select(Station, Depth), phyt_planct_station)


```



```{r}
# Data prepapration

bent_N <- bent %>% filter(Type == "Abundance") %>% select(-Type) 
row.names(bent_N) <- bent_N$Station

totals <- bent_N %>% select(-Station) %>%  rowwise() %>% mutate(Total_N = sum())


predictors2 <- merge(predictors, bent_N)[ ,1:10 ]

bent_N <- merge(predictors, bent_N) %>% select(-c(2:10))


# Remove station with zero benthos abundance

Total_N <- bent_N %>% select(-Station) %>% rowSums()

bent_N2 <- bent_N %>% filter(Total_N>0)

predictors3 <- predictors2 %>% filter(Total_N>0)



```


```{r}
# Ordination in CA 


bent_ca <- cca((bent_N2[, -1]))

bent_pca.ef <- envfit(bent_ca ~ Cyanophyta +  Bacillariophyta + Chrysophyta + Euglenophyta, data = predictors3[, -1])

plot(bent_ca)
plot(bent_pca.ef)
```


