---
title: 'Рыбохозяйственная характеристика акватории Кандалакшского залива Белого моря,
  подходного фарватера к морскому нефтеналивному специализированному порту "Витино"
  попадающей в границы хозяйственной деятельности по объекту: Ремонтное черпание подходного фарватера к морскому нефтеналивному специализированному порту Витино'
output:
  word_document:
    reference_docx: article_template.docx
    fig_width: 8
    fig_height: 5
bibliography: farvater_bibliography.bib
csl: GOST.csl
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Определения и термины

**Акватория** - водное пространство в пределах естественных, искусственных или условных границ; акватория воздействия - акватория, на которой осуществлялось или будет осуществляться антропогенное воздействие, а также сопредельная акватория, на которой сказывается это антропогенное воздействие. В данной работе рассматривается только морская акватория вершины Кандалакшского залива или, если специально оговаривается, акватория прилежащая непосредственно к зоне прохождения фарватера.

**Бентос** - совокупность организмов, всю жизнь или большую ее часть обитающих на дне морских и пресноводных водоемов, в его грунте и на грунте. Различают фитобентос и зообентос.

**Биомасса** - суммарная масса особей вида или группы видов, отнесенная к единице площади или объема (г/м2, г/м3 и др.)

**Видовое разнообразие** - показатель, отражающий не только качественный состав биоценоза, но и количественные взаимоотношения видов.

**Зоопланктон** - совокупность животных, обитающих в толще воды и не способных активно противостоять переносу течениями.

**Индекс стратификации водных масс** -  $n = \frac{\Delta S}{S_{mean}}$, где средняя по глубине соленость воды $S_{mean} = 1/2(S_{surface} + S_{bottom})$, $\Delta S = S_{surface} - S_{bottom}$. Условию хорошего перемешивания отвечает n < 0.1, при n > 1.0 наблюдается сильная стратификация водных масс.


**Индекс видового разнообразия Шеннона** - $H = - \Sigma P_ilog_2{P_i}$, где $P_i$ - доля численности i-го вида в общей численности сообщества. 


**Миграция** - закономерное передвижение животных между значительно отличными местами расселения, иногда связанное с преодолением значительных расстояний


**Нерестилище** - участок водного объекта с комплексом условий, благоприятных для размножения водных организмов в определенный период года.

**Плотность поселения (Численность)** - суммарное количество особей вида или группы видов, отнесенная к единице площади или объема (экз./м2, экз./м3 )

**Рыболовство** - деятельность по добыче водных биоресурсов, а также по их переработке, транспортировке и хранению; промышленное рыболовство (промысел) - предпринимательская деятельность по добыче с использованием специальных технических средств; по приемке, переработке, перегрузке, транспортированию и хранению на рыбопромысловых судах улова и продуктов переработки водных биоресурсов, а также по снабжению рыбопромысловых судов топливом, водой, продовольствием, тарой и другими материалами. Любительское рыболовство - деятельность по добыче с использованием разрешенных надзорными органами средств отлова, как правило имеющих вид крючковой снасти (донки, спиннинги).  

**Фитопланктон** - совокупность микроскопических протист и прокариот, обитающих в толще воды и пассивно передвигающихся под влиянием водных течений.



# Введение 

Подходной фарватер к морскому нефтеналивному специализированному порту «Витино» начал функционировать в 1990-х гг. Важной особенностью фарватера является то, что он практически на всем своем протяжении проходит близко к островам, входящим в состав Кандалакшского Государственного Природного Заповедника и даже заходит в границы ООПТ. Вторая особенность объекта заключается в том, что он, даже будучи проложенным по самым глубоководным участкам подходной акватории, тем не менее, захватывает некоторое количество отмелей, препятствующих безопасному прохождению судов. В связи с этим встает насущная необходимость проведения дноуглубительных работ, которые в свою очередь могут стать источником антропогенных воздействий на природные объекты, в том числе представленные на территории Заповедника. Очевидным объектом техногенного воздействия станет та часть ихтиоценоза вершины Кандалакшского залива Белого моря, которая связана непосредственно с районом предполагаемых работ. В связи с этим необходимо обобщить имеющиеся материалы, которые позволят оценить факторы среды воздействующие на рыб, обитающих на участках связанных с ремонтным черпанием дна в районе прохождения фарватера. К числу факторов, рассмотренных в данной работе, относятся как физико-географические характеристики акватории и ключевые гидрологические факторы, так компоненты биоты (фитопланктон, зоопланктон, зообентос), с которыми потенциально связаны члены ихтиоценоза. 

# Краткая физико-географическая характеристика района работ 

## Географическое описание района проведения работ

Подходной фарватер к нефтеналивному специализированному порту «Витино» начинается на траверзе островов Ломтишных (о. Большой и Малый Ломтишные) на востоке и траверзе пролива между островом Капша и материком (Карельский берег), ведущим в губу Капша (Рис. 1). Далее фарватер следует по узкому проливу, Западной Ряжковой салме, проходящему между материком, на западе, и цепью островов и луд на востоке (самые крупные острова, прилегающие к фарватеру: Куричек, Ряшков). Далее фарватер сворачивает на северо-восток, уходя в пролив Оленья салма (между материком и островом Олений) и заканчивается на подходе к порту «Витино». 

Помимо акватории, непосредственно связанной с фарватером, в проекте будет задействован участок, предназначенный для отвала и захоронения донных грунтов. Этот участок располагается между материком и островами Олений и Телячий, напротив пролива Телячья салма. В этом районе находится участок со значительными глубинами (до 30 м). 





**Рисунок 1.** Вершина Кандалакшского залива. Приведены основные топонимы. На врезке отражена зона прохождения подходного фарватера к специализированному порту «Витино» и предполагаемая зона отвала грунта.

## Краткая характеристика климатических условий

Климатические условия района проведения дноуглубительных работ определяются климатическими параметрами всего региона Белого моря. Они характеризуются относительно теплым летом и длительной суровой зимой [@berger_naumov2001]. В течение всего года в регионе происходят частые смены воздушных масс, при этом большую часть года над регионом присутствуют циклоны, которые приводят к высокой вариабельности (иногда в течение одного дня) метеорологических параметров [@filatov2007white]. 

Наиболее холодное время в регионе наблюдается зимой, когда его захватывают антициклоны, приходящие из Карского моря и северо-запада Сибири. Температура воздуха в этот период может падать до -30° С, иногда даже даже ниже [@berger_naumov2001]. Летняя температура может достигать +30° С, однако в норме она не превышает 15°-20° С [@berger_naumov2001].

Важной особенностью климатических условий вершины Кандалакшского залива Белого моря является образование ледового покрова. Лед держится в акватории с конца ноября до начала апреля. Однако, начиная с 2008 года регулярно наблюдаются события, когда в конце декабря - начале января не происходило формирования ледяного покрова (Рис. 2).  Тренд к потеплению климата выражается и в снижении толщины ледового покрова, которое было прослежено на протяжении многих лет на акватории Кандалакшского залива (@khaitov2012_ice, Рис. 2). 

Тренд глобального потепления в вершине Кандалакшского залива отчетливо прослеживается и по результатам мониторинга температуры воздуха на о. Ряшкове, находящемся в непосредственной близости от района фарватера. За период наблюдений (с 2007 года) средняя температура воздуха в летний период существенно возросла (Рис. 3) и в последние 5 лет превышает среднее значение полученное за период наблюдений.



**Рисунок 2.** Многолетние изменения толщины льда в конце декабря - начале января по данным наблюдений за 1988 - 2016 гг. (По архивным данным Кандалакшского заповедника)  

 

**Рисунок 3.** Многолетняя динамика температуры воздуха в летние месяцы по результатам мониторинга на о. Ряшкове. Среднее значение за период мониторинга отражено горизонтальной пунктирной линией. (По архивным данным Кандалакшского заповедника)
 

Ветровая нагрузка в летний период характеризуется преобладанием ветров северных, северо-восточных, южных и юго-восточных  румбов (@khaitov2012_hydrology; @khaitov2014_hydrology; @khaitov2015_hydrology, рис. 4). При этом самыми слабыми являются ветры северных румбов, что связано с формой рельефа в регионе. Ветры идущие с южного направления не встречают преград и достигают наибольших скоростей (@khaitov2012_hydrology, рис. 5). 




**Рисунок 4.** Частота наблюдения ветров с разным направлением в районе Кандалакши. (По архивным данным Кандалакшского заповедника)



 
**Рисунок 5.** Средняя скорость ветров (±95% доверительный интервал) разных направлений в районе Кандалакши (наблюдения 2011 г.). (По архивным данным Кандалакшского заповедника)

 


## Гидрологические условия 

Характер стационарных течений в вершине Кандалакшского залива сложен и изучен недостаточно. Средняя скорость стабильных течений во всем Белом море относительно слаба и составляет не более 10-20 см/сек [@berger_naumov2001]. Наиболее выраженное стационарное течение в Кандалакшском заливе несет воды вдоль Карельского берега к выходу из залива со скоростью не превышающей 0.1 узла, или около 5 см/сек [@simonov1991]. Более подробные сведения о течениях отсутствуют, но могут быть оценены по косвенным данным (см. ниже)

На фоне слабо выраженных стационарных течений, движение воды, вызванное полусуточными приливно-отливными колебаниями может быть весьма мощным.  Наиболее сильные течения наблюдаются в узких проливах, в том числе в Западной Ряжковой салме, по которой проходит фарватер.


## Характеристика водной массы

Вершина Кандалакшского залива Белого моря характеризуется выраженными градиентами многих экологических факторов, которые изменяются как в горизонтальном, так и в вертикальном (по глубине) направлении. В первую очередь такие градиенты демонстрируют соленость и температура воды. Во многом, пространственная изменчивость этих двух показателей связана с влиянием крупных рек, впадающих в Кандалакшский залив. Самыми крупными водотоками в районе, прилегающем к подходному фарватеру к порту «Витино», являются реки Нива, Колвица сток из губы Канда, а также охладительный канал Нивской ГЭС. Помимо этих водотоков, играющих ведущую роль в формировании паттерна распределения солености, в акваторию впадают и малые реки (Капша, Лувеньга, Лупче-Савино), а также многочисленные ручьи. 

Соленостный режим акватории, в том числе, зависит и от сезонных явлений. Наиболее сильное опреснение, затрагивающее верхние 2-3 м наблюдается в период таяния льда, приходящийся на апрель - май [@simonov1991].  

Результаты картирования поверхностной солености в вершине Кандалакшского залива (@khaitov2016_salinity; оригинальные данные, собранные в 2024 г., Рис. 6) позволили выявить несколько закономерностей. Во-первых, в акватории наблюдается отчетливый пространственный градиент, характеризующийся минимальной соленостью в куту залива и постепенным ее повышением по мере движения от кута к открытой части акватории. Во-вторых, общая форма этого градиента воспроизводится в разные годы. И, в третьих, зона распространения языка пресной воды, связанного в первую очередь с влиянием сброса из реки Нивы и охладительного канала «Нивской» ГЭС, вытянута вдоль Карельского берега. Участки акватории, расположенные вдоль Кандалакшского берега не подвергаются значительному опреснению. Это хорошо согласуется с общим паттерном течений, описанным выше и может рассматриваться в качестве косвенного доказательства наличия стационарного течения, в том числе и в кутовой части Кандалакшского залива. Таким образом, влияние сброса пресной воды в вершине Кандалакшского залива будет оказывать наиболее сильное влияние на участки акватории, прилегающие к Карельскому берегу. Именно в этой зоне представлены биосистемы, находящиеся в зоне потенциального влияния дноуглубительных работ.



**Рисунок 6.** Точки отбора проб и карты пространственного распределения значений поверхностной солености в 2015 и 2024 гг. Карта составлена с помощью построенной аддитивной обобщенной модели, связывающей соленость с географическими координатами и годом сбора материала. (По архивным данным Кандалакшского заповедника)


Поскольку для морских биосистем важны не только характеристики поверхностных вод, важно рассмотреть также и то, как устроена вертикальная структура водной массы. Фоновая соленость в Кандалакшском заливе составляет 20-21%~о~ на поверхности и около 25-26%~о~ в придонном слое со средним вертикальным градиентом 0.25%~о~ на 1 м [@pantiulin1994]. Индекс стратификации водных масс (параметр стратификации, n=0.22) соответствует условиям частичного перемешивания вод [@pantiulin1994]. Однако в кутовой части акватории Кандалакшского залива появляется существенно более сильная стратификация вод. По данным съемки в 1991 г. на станции расположенной в районе о. Б. Лупчострова, вертикальный градиент солености составил 2.26 %~о~ на 1 м, параметр стратификации вод был значительно выше, чем в целом по акватории залива, n = 0.72 . Резкий скачек солености был отмечен на глубине около 5 м [@pantiulin1994]. Эти данные хорошо согласуются с результатами обследования акватории в 2007 г., проведенном на большем количестве гидрологических станций  (@khaitov2008_salinity, Рис. 7). Эти результаты оказались аналогичны полученным ранее: скачек солености происходит на глубине около 5 м. На глубине более 10 м соленость остается неизменной и составляет около 25 %~о~.



**Рисунок 7**. Соленость воды на разных горизонтах глубины (бокс-плоты и синие точки) по данным гидрологической съемки в вершине Кандалакшского залива в  2007 г. и распределение солености по горизонтам глубины в границах подходного фарватера на траверзе о. Ряшкова (район буя № 19) по данным съемки 2024 г (красные точки). (По архивным данным Кандалакшского заповедника)


Стратификация воды в районе фарватера, оцененная во время малой воды, выражена значительно слабее (Рис. 7).  Это, вероятно, связано с сильными течениями, перемешивающими опресненную воду, идущую из кута залива, и придонную воду с нормальной морской водой. 

Для более надежной оценки структуры водных масс необходимо учитывать значения не только солености, но и температуры воды. Картину циркуляции водных масс в районе, непосредственно прилегающем к фарватеру, отчасти позволяют реконструировать ежесуточные наблюдения, которые осуществляются в течение всего летнего периода в точке, расположенной в Южной губе о. Ряшкова, в 900 м от восточной границы фарватера (67.007506 N; 32.574637 E). Многолетние наблюдения в этой точке показывают, что между соленостью и температурой воды во все годы наблюдений наблюдалась отчетливая, статистически значимая отрицательная корреляция (Рис. 8)


**Рисунок 8**. Связь солености и температуры воды в Южной губе o. Ряжкова в летний период (По архивным данным Кандалакшского заповедника)



**Рисунок 9.**  T-S диаграмма для летних водных масс Южной губы о. Ряжкова. Контуры соответствуют оценке ядерной плотности распределения точек. (По архивным данным Кандалакшского заповедника)

Обобщение всех данных, полученных за весь период наблюдений (ежегодно, начиная 2007 г., Рис. 9),  позволяет выделить некоторую гетерогенность в поверхностной водной массе. На Рис. 9 отчетливо выделяются два скопления точек, что свидетельствует о прохождении через акваторию Южной губы двух водных масс. Первая масса - имеет более высокую соленость (более 19 промилле), вероятно, соответствует обычной поверхностной летней водной массе, характерной для Белого моря. Эта водная масса демонстрирует широкие колебания температуры. Видимо, это связано с постепенным прогревом этих вод в течение лета. Вторая водная масса имеет соленость ниже 19 промилле и характеризуется более высокой температурой, варьирующей в узких пределах. Более «компактный» характер второй водной массы позволяет предположить, что она присутствует в акватории очень короткое время, довольно быстро ассимилируясь с господствующей здесь основной, первой водной массой. Происхождение этой водной массы можно связать с антропогенным влиянием, связанным с регулярными сбросами пресной воды из водохранилища «Нивской» ГЭС (см. ниже)

 
**Рисунок 10.** Многолетняя динамика фенологических характеристик поверхностной водной массы. Левая панель описывает изменение солености. Изолиния проведена с шагом в 5 промилле. Правая панель - изменение  температуры воды в Южной губе. Изолинии проведены с шагом в 5 градусов. (По архивным данным Кандалакшского заповедника)

Характеристики водной массы, проходящей через акваторию, достаточно закономерно изменяются в течение летних месяцев [@khaitov2023_hydrology_phenology]. Более соленая и холодная вода обычно присутствует в акватории в июне. В августе наблюдается заметное опреснение и повышение температуры воды. Отмечаются и некоторые многолетние тренды. Например, после 2011 года отмечается устойчивое формирование более пресной и теплой водной массы в более ранние сроки. Вода с такими характеристиками отмечается уже в конце июля. 

На характеристики водных масс оказывают, также, и внезапные, не связанные с сезонностью, события. Так, например, значительную роль играют периодически осуществляемые сбросы пресной воды из водохранилища «Нивской» ГЭС. Одно из самых мощных воздействий было отмечено в 2000 году [@koriakin2001_influence], когда сброс пресной воды привел к катастрофическим последствиям: значительное количество поселений литоральных беспозвоночных в кутовой части залива погибло [@koriakin2001_regulation]. Поселение мидий на банке, расположенной в проливе между о. Олений и Телячий, не восстановилось даже спустя полтора десятилетия после этого воздействия [@shklarevich_moiseeva2015].

Ежедневные наблюдения над гидрологическими параметрами в Южной губе о. Ряшкова, проведенные в 2015 г. (@khaitov2016_hydrology, Рис. 11) позволили оценить скорость распространения «языка» распреснения, вызванного сбросом с «Нивской» ГЭС. Так, в перовой декаде июня 2015 г. был отмечен очередной сброс пресной воды из водохранилища. Сопоставление динамики солености и температуры воды (Рис. 11) показывает, что уже во второй половине июня наблюдался резкий скачек в показателях: соленость снизилась, а температура воды возросла. Далее, несмотря на характерные для этих показателей колебания в противофазе (отрицательная корреляция между температурой воды и соленостью), соленость оставалась на достаточно низком, а температура - высоком уровне. При этом, если температура воды в этот период приблизилась к среднему за предыдущие годы значению, то соленость оказалась заметно ниже аналогичного среднего. Полученная аномалия хорошо согласуется с фактом мощного сброса воды с водохранилища Нивской ГЭС. Таким образом, от устья реки Нива, через которую и осуществляются антропогенные сбросы пресной воды, до Южной губы о. Ряжкова волна поверхностного распреснения дошла приблизительно за две недели. Учитывая, что расстояние от устья р. Нива до Южной губы (с учетом огибания островов) составляет около 20 км можно оценить скорость перемещения сброшенных вод в 1.7 см/сек. Эта величина того же порядка, что и оценка скорости стационарного течения, идущего вдоль Карельского берега к выходу из Кандалакшского залива (см. выше). Эти наблюдения могут рассматриваться как еще одно косвенное доказательство наличия стационарного течения несущего воду в том числе и из района захоронения отвалов грунта по Западной Ряжковой салме, где проходит фарватер.   

**Рисунок 11.** Динамика солености и температуры воды в Южной губе летом 2015 г. Горизонтальная пунктирная линия представляет среднее значение соответствующего показателя за предыдущие годы. (По архивным данным Кандалакшского заповедника).

Еще одним фактором, регулирующим динамику гидрологических показателей в акватории, прилегающей к фарватеру, явлется ветровое воздействие. Наблюдения позволил заметить, что температура воды демонстрируют статистически значимую зависимость от ветров северных и южных румбов (Рис. 12). Температура воды существенно падает, если дуют сильные ветры северных румбов. Незначительное повышение температуры воды отмечается при сильных ветрах южных румбов. Учитывая, что соленость воды и ее температура сильно взаимосвязаны (см. выше) гидрологический режим в точке наблюдения можно реконструировать следующим образом. При сильном северном ветре температура воды падает, а соленость возрастает.  Эту закономерность можно объяснить следующим образом. При северном ветре поверхностная теплая и опресненная водная масса смещается к выходу из залива, на ее место поднимается более холодная и более соленая глубинная водная масса. При ветрах южных румбов, вероятно, поверхностная водная масса задерживается в акватории вершины залива, что приводит к снижению солености и повышению температуры. 

Такой выход на поверхность соленой и холодной водной массы был задокументрован в 2006 году [@khaitov2008_untypical_water_mass]. В этот год в конце июля - начале августа резко упала температура воды (от характерных для этого времени года 10-15°С до 4-5°С). Практически синхронно было отмечено заметное увеличение солености воды (до 27-28 промилле). В даты, соответствующие всплеску солености в акватории Южной губы было отмечено необычайно высокое количество планктонных животных (гидромедузы и щетинкочелюстные). В это же время неподалеку от места впадения в акваторию залива охладительного канала Нивской ГЭС местными жителями было отмечено большое количество ракообразных, выброшенных на берег. Основную массу выброшенных животных составляли бокоплавы (подотряд Hyperiidea) и креветки. 


**Рисунок 12.** Зависимость температуры воды в Южной губе от силы ветра разных румбов. На рисунке приведена регрессионная прямая (с 95% доверительными интервалами, пунктирная линия). Горизонтальная прерывистая линия – среднее за все годы значение температуры воды (По архивным данным Кандалакшского заповедника). 


Гидрологические параметры поверхностной водной массы, проходящей через фарватер, демонстрируют существенные межгодовые колебания (Рис. 13). Так, средняя для летних месяцев соленость колеблется год от года, периодически падая ниже или превышая среднее для наблюдаемой акватории значение (Рис. 13). Однако, после 2020 г. наблюдается тенденция к большему опреснению, чем это было в предыдущие годы. На фоне снижающейся солености ожидаемо наблюдается рост температура воды. 



 
**Рисунок 13.** Многолетние изменения солености и температуры воды в акватории, прилегающей к подходному фарватеру (по данным мониторинга Кандалакшского заповедника на о. Ряшкове). Горизонтальная пунктирная линия отражает среднее значение параметра, полученное за период мониторинга (По архивным данным Кандалакшского заповедника).


## Охранные зоны водного объекта 

На акватории вершины Кандалакшского залива располагаются ООПТ Кандалакшского государственного природного заповедника (Рис. 14). Практически на всем протяжении Западной Ряжковой салмы фарватер проходит по территории Заповедника или вплотную подходит к его границам. 


**Рисунок 14.** Границы ООПТ Кандалакшского государственного природного заповедника в вершине Кандалакшского залива. 

 

# Ихтиофауна и рыбохозяйственное значение 

## Видовой состав рыбного населения 

Планомерных обследований рыбохозяйственных свойств вершины Кандалакшского залива за последние несколько десятлетий не проводилось.  Это связано с отсутсивем промышленного лова рыбы в этом районе. В настоящее время акватория вершины Кандалакшского залива активно используется только для любительского промысла. Единственное предприятие, которое имеет прямое отношение к рыбопромысловой активности - это Кандалакшский экспериментальный лососевый завод, который располагается на левом берегу реки Нива (в 2 км от устья). Производственная мощность завода по выпуску молоди семги составляет до 187 тыс. штук годовиков в год (https://cyclowiki.org/wiki/Кандалакшский_экспериментальный_лососёвый_завод). 

Единственным источником информации об ихтиоценозе непосредственно в районе прохождения фарватера являются наблюдения, проводящиеся Кандалакшским государственным заповедником. Ниже приводятся данные только по ихтиценозу морских и солоноватоводных рыб, постоянно отмечающихся или периодически заходящих в Кандалакшский залив Белого моря. Анализ данных архивов Кандалакшского заповедника показал, что в морской акватории и эстуариях встречается 1 вид круглоротых, 4 вида хрящевых рыб и 45 видов костистых рыб (Табл. 1).

**Таблица 1.** Список видов рыбообразных и рыб, отмеченных в вершине Кандалакшского залива (по данным прхивов Кандалакшского заповедника)



## Обилие рыб 

К числу наиболее частых видов рыб, постоянно держащихся или периодически заходящих в акваторию вершины Кандалакшского залива, относятся два вида сельди, горбуша, беломорская треска, навага, а в последние годы и трехиглая колюшка. Эти виды, за исключением, на современном этапе, трехиглой колюшки, играют наиболее важную роль в любительском промысле местного населения.

Обилие сельди, как основного промыслового вида рыб Белого моря, демонстрировало значительное сокращение на протяжении XX в. За столетие уровень добычи сельди сократился в десять раз. Это связано как с интенсификацией вылова за счет применения более совершенных орудий лова, так и с сокращением обилия взморника, *Zostera marina* (см. ниже), служащего основным субстратом для откладки икры [@berger2001]. В настоящее время промышленного лова сельди в вершине Кандалакшского залива не проводится, однако практикуется любительский лов. На конец XX в. запасы всей популяции беломорской сельди оценивались в 5000-7000 тонн [@berger2001].

Значительную роль в традиционном промысле населения составляет атлантический лосось (семга). Однако, из-за сокращения численности популяции этого вида, его лов строго лицензирован. Вместе с тем, судя по наблюдениям сотрудников Кандалакшского заповедника, браконьерский лов семги в вершине Кандалакшского залива не редок. Оценок численности поголовья этого вида в вершине Кандалакшского залива не проводилось

Интродуцированная в Белое море горбуша демонстрирует периодические (в нечетные годы) массовые нерестовые подходы к рекам, впадающим в вершину Кандалакшского залива (в первую очередь реку Лувеньга). В 2021 в устье р. Лувеньги ежедневно скапливалось по нескольку сотен рыбаков, осуществлявших лов горбуши. Это свидетельствует о значительном обилии горбуши. Ожидаемый подход в 2023 г. не оправдался, вылов горбуши осуществлялся в обычных объемах (со слов местных рыбаков 1-2 особи за сутки).

Одним из самых массовых видов рыб ихтиоценоза вершины Кандалакшского залива является трехиглая коюшка. По историческим данным, в конце XIX в. в Белом море наблюдался промысел этой рыбы, добыча достигала 30 тыс. особей за один замет невода [@lajus2020_review]. По свидетельствам местного населения, еще в 1940-1950-е годы вяленую колюшку массово заготавливали для длительного хранения. В середине XX в. численность колюшки резко сократилась [@lajus2013_vawes_of_life]. Однако в настоящее время происходит восстановление ее популяции. Сейчас численность вида составляет до 176 экз./м^2^ [@ivanova2016white].

Обилие трески и наваги в вершине Кандалакшского залива можно оценить лишь весьма приблизительно, так как промышленного лова этих видов в описываемом районе не ведется и статистические данные отсутствуют. По данным, полученным на конец XX в. запасы трески в Кандалакшском заливе составляли 6.5-7.5 млн. особей, или 1700-2000 тонн [@berger2001]. Однако, вероятно, в XXI веке происходило увеличение численности популяции этого вида. Об этом позволяют судить контрольные отловы, которые проводят в Кандалакшском заповеднике ежегодно в течение всего лета. Отловы проводятся с помощью крючковой снасти, соответствующей снастям любительского рыболовства придонных рыб. В число рыб, поддающихся такому учету относятся треска и навага (Рис. 15). Остальные виды рыб на такую снасть ловятся крайне редко. 

В среднем (при объединении данных за много лет), за час на одну удочку попадается 5.7 особей трески и 1.6 наваги. За последние годы численность трески возросла (в 2013-2015 и 2023 гг уловы были выше многолетнего среднего), в то время как обилие наваги упало практически до нуля. 



**Рисунок 15.** Многолетние изменения численности трески и наваги в контрольных отловах в районах соседствующих с зоной прохождения подходного фарватера. Пунктирная линия отражает многолетнее среднее значение численности отловленных рыб. Сплошная синяя линия регрессии отражает многолетнюю тенденцию.




## Нерестилища 	

*Сельдь*

Мелкая сельдь, или егорьевская (длина 15-17 см) нерестится в апреле - начале мая, крупная, или ивановская сельдь (длина 20-30 см), нерестится в июне [@ivanchenko1991]. Естественные нерестилища сельди связаны с зарослями взморника, *Zostera marina* [@berger2001]. В вершине Кандалакшского залива нерестилища сосредоточены в северо-западной части акватории от губы Княжая до самой кутовой части залива [@ivanchenko1991].

*Семга*

Основные преднерестовые скопления атлатического лосося сосредоточены за пределами Кандалкшского залива и формируются, в основном, в Мезенском, Двинском и Онежском заливах Белого моря [@studenov1991]. В вершине Кандалкшского залива наиболее пригодные для нереста семги реки были перекрыты плотинами ГЭС (Нивская и Княжегубская), что сделало эти реки непригодными для нереста. Однако, судя по косвенным признакам (наблюдения за активностью браконьеров), в некоторые малые реки (например в ручей Капша, впадающий в одноименную губу) нерестовые заходы семги осуществляются. 


*Треска* 

Основные нерестилища беломоской трески в Кандалакшском заливе находятся за пределеами описывемой акватории. Они располагаются ближе к выходу из залива. Онако в вершне Кандалакшского залива отмечено две зоны, где проходит нерест трески [@stasenkov1991]. Одно располагается в Кибирнской салме на траверзе устья губы Колвица. Второе описанное нерестилище находится непосредственно в зоне прохождения фарватера и представлено в районе Палкиной губы на границе межу Западной Ряжковой и Оленьей салмами [@stasenkov1991]. 

*Навага*

Основные нерестилища этого вида сосредоточены за пределами описываемой акватории (Berger, 2001). Однако небольшое нерестилище наваги отмечено на границе описываемой акватории, на траверзе южного побережья губы Княжая [@stasenkov1991].  

*Трехиглая колюшка*

Нерестится Кандалакшском заливе посеместно, в затишных местах с развитыми зарослями зостеры и/или нитчатых водорослей. Нерест, также, может проходить и в поясе фукоидов. Численность нерестящихся особей, в среднем, составляет   80 экз./м^2^ в зарослях морской травы и до 15 экз./м^2^ в фукоидах [@lajus2020_review].

## Пути и сроки миграций рыб

Пути миграции рыб в вершине Кандалакшского залива изучены крайне фрагментарно. 
Основные пути нерествых миграций семги лежат за пределами Кандалакшского залива [@studenov1991]. Однако, по свидетельству местных жителей и наблюдению за активностью браконьеров, в небольших водотоках, впадающих в вершину Кандалакшского залива, нерест семги происходит. Это позволяет предположить, что некоторая часть популяции атлантического лосося мигрирует также и в вершину Кандалакшского залива.  

Наиболее изучены миграции беломорской сельди. Так, рыбы, обитающие в вершине Кандалакшского залива, после нереста (у егорьевской сельди в апреле-мае, а у ивановской - в июне) осуществляют миграции в восточном направлении, двигаясь к выходу из залива вдоль Терского берега [@berger2001]. После нагула в юго-восточной части Кандалакшского залива, сельдь совершает зимовальные миграции в сторону вершины залива [@ivanchenko1991].

У тресковых рыб миграционные процессы связаны с изменеием образа жизни входе жизненного цикла. Так, у беломорской трески развитие икры и вылупление личинок происходит в толще воды (март-май). Пелагические стадии развития трески разносятся течениями. В Кандалакшском заливе пелагические личинки трески встречаются в конце мая, но уже в середине лета (июль) ювенильные особи опускаются на дно [@berger2001]. Миграции тресковых рыб могут регулироваться и сезонными изменениями гидрологических показателей. Так старые особи холодолюбивой наваги в июле-августе, когда прогревается поверхностная водная масса, мигрируют на большую глубину (20-30 м), более молодые особи остаются на меньших глубинах. Однако уже в сентябре-октябре, когда вода охлаждается, происходит возвращение старых особей в область меньших глубин [@berger2001]. Описана также нагульная миграция наваги от нерестилища в районе губы Княжая (см. выше) в северо-восточном направлении в сторону губы Колвица [@stasenkov1991].

Отчетливо выраженные миграции демонстрирует трехиглая колюшка. Молодь этого вида появлется на мелководьях Кандалакшского залива в июле. К августу ее численность достигает максимума. В начале сентября подросшие мальки мигрируют в открытое море, где, судя по всему, ведут пелагический образ жизни [@lajus2020_review]. К берегам вершины Кандалакшского залива половозрелые особи подходят в конце мая - июне [@bojko2024].  



# Характеристика биоценотического окружения и кормовой базы рыб 

Основными компонентами экосистемы вершины Кандалакшского залива, обеспечивающими поддержание ихтиоценоза, являются заросли морских макрофитов, фитопланктон, зоопланктон и зообентос. Механизмы влияния указанных компонентов можно разделить на три группы. Во-первых, это кормовая база рыб. Для  планктоядных рыб (сельдь) эту функцию выполняют компоненты зоопланктона и, в меньшей степени, фитопланктона. Для бентофагов (треска, зубатка, камбала, колюшка) основу питания составляет зообентос. Во-вторых, создание биогенной среды, в которой обитают как сами рыбы, так и их кормовые объекты. Эту функцию в большей степени выполняют донные макрофиты, в зарослях которых формируются сообщества, где происходит откорм рыб. В меньшей степени эту роль играют двустворчатые моллюски, формирующие плотные скопления. В-третьих, это создание субстрата для нереста. Эту роль на себя берут донные макрофиты (в первую очередь, зостера и, в меньшей степени, фукоиды и нитчатые водоросли). 

## Планктон

### Условия среды

Состав планктона в прибрежной зоне Кандалакшского залива Белого моря определяется физико-географическими условиями в данном районе, прежде всего, термогалинными. В течение года эти условия в верхнем наиболее населенном слое воды изменяются от арктических зимой до бореальных летом. При этом размах изменения температуры в течение одного года может достигать 20°С [@babkov1982]. Зимой средняя температура верхнего 25-метрового слоя воды опускается до -1°С, а летом может подниматься выше 10°С (рис. 16; @babkov1982; @usov2024joint). Минимальные температуры обычно имеют место в марте-апреле, в конце гидрологической зимы, а максимальные – в июле-августе, в середине гидрологического лета (Бабков, 1985). Такое разнообразие условий в течение года позволяет сосуществовать в планктоне видам самого разного биогеографического происхождения – бореальным, арктическо-бореальным и арктическим, соотношение которых изменяется в течение года по мере изменения внешних условий. 


**Рисунок 16.** Сезонная динамика температуры воды и степени стратификации верхнего слоя водной толщи (разность плотности воды между глубиной 1 и 20 м).


## Фитопланктон

В планктоне вершины Кандалакшского залива отмечено как минимум 185 видов планктонных водорослей [@usov2024joint; @ilyash2018phytoplankton]. Основные таксономические группы фитопланктона (цифры в скобках – число видов): Bacillariophyceae (Heterokontophyta) (34), Mediophyceae (Heterokontophyta) (28), Coscinodiscophyceae (Heterokontophyta) (14), Dinoflagellata (45), Chlorophyta (14), Cyanobacteria (4), Euglenophyta (3), Dictyochophyceae (Heterokontophyta) (3), Chrysophyceae (Heterokontophyta) (2), Charophyta (2), Haptophyta (1), Thecofilosea (Cercozoa) (1) and Katablepharidophyceae (Cryptista) (1) [@usov2024joint].

Интенсивность фотосинтеза регулируется освещенностью и температурой воды, причем последняя выступает на первый план, когда освещенность достигает насыщения  [@tilzer1986light]. Важным фактором является также степень стратификации водной толщи [@usov2024joint]. Последний показатель изменяется в течение года в широких пределах, и максимум этого показателя совпадает с началом наиболее теплого периода года (рис. 16). В прибрежье Кандалакшского залива зимой, в условиях слабой освещенности и низких температур биомасса фитопланктона в поверхностном слое не превышает 13 мг/м^3^, а численность – 0.08х10^9^ кл./м^3^ [@usov2024joint]. В течение года в среднем наблюдается два-три пика численности планктонных водорослей: весенний – в мае-июне, летний – в июле-августе и осенний в сентябре [@kokin1970; @khlebovich1974; @usov2024joint]. При этом весенний (в начале июня) пик в 2017 г. достигал 1.45х10^9^ кл./м^3^, летний (в августе) – 2.6 х10^9^ кл./м^3^, осенний (в сентябре) – 2.9 х10^9^ кл./м^3^ (рис. 17; U @usov2024joint), был зарегистрирован еще и зимний скачок численности в конце марта – 1.7 х10^9^ кл./м^3^. В тот же год зарегистрировано три пика биомассы: зимний в конце марта (866 мг/м^3^), весенний в мае (1611 мг/м^3^) и летний в начале августа (683 мг/м^3^). В 1967-1968 гг. зарегистрированы также три пика численности весной (в начале мая), летом (в июле) и осенью (в сентябре): 0.13 х10^9^ кл./м^3^, 1.5 х10^9^ кл./м^3^ и 0.32 х10^9^ кл./м^3^, соответственно [@kokin1970]. При этом в 1960-е гг. отмечено также три пика биомассы: в мае (104 мг/м^3^), июле (103 мг/м^3^) и августе (103 мг/м^3^). 


**Рисунок 17.** Сезонная динамика биомассы и численности фитопланктона в прибрежной зоне Кандалакшского залива по данным 2017 г. [@usov2024joint].

Как видно, для обилия фитопланктона характерна значительная многолетняя изменчивость. К сожалению, невозможно проследить долговременные тренды динамики, так как исследования фитопланктона проводились крайне нерегулярно, в разных районах и по разной методике. Однако можно утверждать, что последовательность появления основных групп фитопланктона в течение вегетативного сезона остается более-менее постоянной. В начале сезона, во время весеннего цветения, преобладают диатомовые водоросли (Bacillariophyceae, Mediophyceae, Coscinodiscophyceae), которых сменяют по мере прогрева водной толщи динофлагелляты [@usov2024joint; @ilyash2018phytoplankton]. Менее богатые видами Cryptophyta, Chlorophyta, Dictyochophyceae, Euglenophyta входят в группу доминант летом и осенью (рис. 18; @usov2024joint).





**Рисунок 18.** Соотношение доминантных групп фитопланктона в течение года в прибрежье Кандалакшского залива [@usov2024joint].

## Зоопланктон

В зоопланктоне Кандалакшского залива Белого моря обнаружен 46 видов истинно планктонных многоклеточных животных: 26 видов ракообразных (Crustacea), 11 видов стрекающих (Cnidaria), 2 гребневиков (Ctenophora), 2 коловраток (Rotifera), 2 крылоногих моллюсков (Pteropoda), 1 вид щетинкочелюстных (Chaetognatha) и 2 вида аппендикулярий (Larvacea) (Усов, 2015). Среди ракообразных, как и в других морях высоких широт, подавляющая часть видов (17) – это веслоногие ракообразные (Copepoda). Кроме того, в планктоне присутствуют личинки донных животных: Mollusca (Bivalvia, Gastropoda), Polychaeta, Cirripedia, Echinodermata, Ascidia, Bryozoa, которые в теплое время года достигают значительной численности и биомассы. И по численности, и по биомассе в планктоне доминируют веслоногие ракообразные, составляя более 90% от общей численности и биомассы зоопланктона  [@kosobokova2012; @usov2015].

В течение года в прибрежье Кандалакшского залива наблюдается, как правило, один пик численности зоопланктона – в июле, когда, согласно многолетним данным, численность достигает 68000 экз./м^3^ (рис. 19; @usov2024joint). Максимум биомассы зоопланктона (ок. 800 мг/м^3^) наблюдается июне – начале июля, когда в планктоне в массе присутствует молодь крупных арктических видов Copepoda (рис. 19; @kosobokova2012; @usov2015). Минимальные значения обилия зоопланктона отмечены в зимний период: в январе-феврале численность опускается ниже 3000 экз./м^3^, биомасса – ниже 150 мг/м^3^. 

**Рисунок 19.** Сезонная динамика биомассы и численности зоопланктона в прибрежной зоне Кандалакшского залива по многолетним данным. Приведены стандартные ошибки среднего.

В течение года в верхнем продуктивном слое водной толщи (0-25 м) сменяется четыре сезонные группировки видов (рис. 20; @usov2024joint), сроки присутствия которых в планктоне соответствуют в целом гидрологическим сезонам. Во всех группировках доминируют веслоногие ракообразные, только летом на первое место выходит щетинкочелюстное *Parasagitta elegans*. Наиболее многочисленными видами в Кандалакшском заливе являются арктическо-бореальные *Pseudocalanus minutus*, *P. acuspes* и вид-космополит *Oithona similis* [@usov2024joint]. Важное значение имеет крупный арктический вид *Calanus glacialis*, который доминирует по биомассе в весенний период [@kosobokova2012; @kosobokova1999reproductive]. Кроме того, этот вид, наряду с *Pseudocalanus* spp. – основные пищевые объекты беломорской сельди [@gerasimova1991]. 



**Рисунок 20.** Сезонные группировки зоопланктона в прибрежье Кандалакшского залива.

В течение года изменяется также вертикальное распределение планктонных животных – по мере прогрева воды холодноводные организмы смещаются в более глубокие и холодные слои. Так, почти вся популяция арктического **Calanus glacialis**, кроме самых младших стадий развития, к июлю смещается глубже 25 м [@prygunkova1974]. То же самое происходит со старшими стадиями развития *Pseudocalanus* spp. Такие миграции называют онтогенетическими, поскольку животные мигрируют по мере смены стадий развития. Бореальные (тепловодные) животные не совершают миграций, так как условия в верхнем слое воды даже в летний период не выходят за пределы оптимальных для них.

В прибрежье Кандалакшского залива отмечены значительные межгодовые изменения обилия зоопланктона (рис. 21; @usov2021phenological). В динамике некоторых видов можно проследить многолетние квазициклические колебания (рис. 22; @usov2021phenological), причем, как видно, длина периода может быть от нескольких лет до нескольких десятилетий. 



**Рисунок 21.** Многолетняя динамика зоопланктона в прибрежье Кандалакшского залива. Приведены среднегодовые значения. 


**Рисунок 22.** Квазициклические колебания численности молоди Calanus glacialis и Pseudocalanus spp. в Кандалакшском заливе. 



## Бентос

Бентосные сообщества в вершине Кандалакшского залива исследованы достаточно полно. Однако основные точки сбора материала концентрируются в некоторых ключевых участках акватории (станции мониторинга, описания некоторых наиболее интересных и важных участков и т.п.), что делает их весьма изученными. Иные участки акватории исследованы хуже или не описаны вовсе. На такие участки акватории могут быть экстраполированы данные, полученные на изученных участках. 

Приведенные ниже данные базируются на следующих источниках:   
1.Главы Летописи природы Кандалакшского заповедника.    

2.Опубликованные работы.    

3.Отчеты Зоологического института РАН о работе по экологическому мониторингу акватории морского специализированного порта «Витино» за разные годы.     

4.Архивы Кандалакшского заповедника (неопубликованные отчеты, хранящиеся в библиотеке Заповедника, электронные базы данных).   

### Донные сообщества вершины Кандалакшского залива

#### Видовой состав

Всего в вершине Кандалакшского залива, на акваториях Кандалакшского заповедника, отмечено 559 видов донных беспозвоночных [@grishankov_ninburg_shklarevich2000]. Этот список давно не подвергался ревизии и требует существенных дополнений. В связи с этим, ниже будет дана характеристика видового состава бентоса только для акватории, которая непосредственно прилегает к подходному фарватеру. 

В основу данных, приведенных ниже, легли мониторинговые обследования  донных сообществ Западной Ряжковой салмы, проводимые силами Кандалакшского заповедника, и отчеты, подготовленные ЗИН РАН по договорам с портом «Витино». Карта расположения точек сбора материала приведена на Рис. 23.




**Рисунок 23.** Точки сбора материала по программе мониторинга Кандалакшского заповедника и ЗИН РАН в разные годы. 



Помимо указанных сборов в период с 1964 по 1993 гг силами Кандалакшского заповедника проводилась работа по инвентаризации сообществ макробентоса в окрестностях о. Ряшкова (более 600 дражных и более 100 дночерпательных станций). Многочисленные бентосные количественные и качественные пробы позволили выделить несколько наиболее типичных сообществ, представленных на литорали и в сублиторали вершины Кандалакшского залива. Для визуализации пространственного распределения этих сообществ была построена карта (Рис. 24). Вместе с тем, далеко не все сообщества, отмеченные в акватории, удается визуализировать, так как некоторые из них располагаются небольшими пятнами или очень узкими поясами, что не позволяет их нанести на карту приемлемого масштаба.
 


**Рисунок 24.** Карта распределения сообществ, присутствующих на акватории, прилегающей к подходному фарватеру к специализированному порту «Витино». 1. Сообщество гравийно-галичных промытых грунтов; 2. Сообщество мелководных илов; 3. Сообщество глубоководных илов; 4. Заросли багрянок; 5. Заросли ламинарии. (По архивным данным Кандалакшского заповедника).




**Заросли зостеры**

Формируются цветковыми растениями *Zostera marina** Linnaeus. Поселения представлены  на илисто-песчаных пляжах на нижнем горизонте литорали и заходят в верхнюю часть сублиторали. Хорошо известное и задокументированное массовое отмирание зостеры, произошедшее по всему северо-западу Европы в середине XX века  [@den1987wasting], затронуло и Белое море. Однако в последние несколько десятилетий в вершине Кандалакшского залива происходит постепенное восстановление зарослей взморника [@maksimovich2004]. 

Наиболее мощные заросли в районе прохождения фарватера отмечены на литорали островов Ряшков и Б. Медвежий. Здесь на 1 погонный метр береговой линии приходится около 2 м^2^ зарослей [@savitskaya2010]. В состав сообщества, связанного с зарослями зостеры, входит небольшое количество видов  [@rydlovskaya1997]. Наиболее типичными обитателями являются брюхоногие моллюски *Peringia ulvae* и двустворчатые моллюски *Mytilus* spp. и *Macoma balthica* (Табл. 2).  

Сообщество с доминированием зостеры являются наиболее предпочитаемым для откладки икры беломорской сельди [@ivanchenko1991]. К зарослям зостеры также приурочены нерестилища трехиглой колюшки [@lajus2020_review]. 


**Таблица 2.** Биомасса (г/м2) и плотность поселения (экз/м2) наиболее обильных видов, населяющих заросли зостеры в вершине Кандалакшского залива (из Рыдловская, 1997).



**Заросли зеленых нитчатых водорослей**

В формировании плотных матов нитчатых водорослей принимают участие несколько видов, из которых наиболее обильными являются *Cladophora* spp. и *Ulvae* spp. Скопления этих быстро растущих водорослей, как правило, приурочены к затишным участкам литорали, с хорошо выраженными источниками биогенов. В качестве последних могут выступать источники антропогенного происхождения, например в районе бытовых стоков с городских и сельских агломераций. Поэтому в акваториях, соседствующих с поселениями человека, обычно наблюдается буйный рост нитчаток. Помимо этого бурное развитие этих водорослей происходит в кутах мелководных губ и полуизолированных лагунах, где происходит аккумуляция детрита. Кроме того, мощные скопления мидий (мидевые банки) также являются источниками биогенов. Поэтому вокруг мидиевых банок и на их поверхности всегда присутствуют скопления нитчатых водорослей. 

В районе прохождения фарватера такие заросли обнаружены в кутовой части Южной губы о. Ряшкова, на мелководьях, прилегающих к восточному побережью Луды Девичьей и Северо-западному берегу о. Б. Ломтишный. Заросли нитчаток также представлены в губе Коровьей (о. Олений) и в лагунах о. Телячьего,  которые находятся в непосредственной близости от терминала порта «Витино». Количественного описания сообщества, связанного с зарослями нитчатых водорослей не прводилось.

Заросли нитчаток в вершине Кандалакшского залива являются, наряду с зарослями зостеры, излюбленным биотопом, в котором самцы трехиглой колюшки строят гнезда и выращивают мальков. 


**Заросли фукоидов**

Пояс фукоидов в вершине Кандалакшского залива сформирован, в основном, тремя видами бурых водорослей *Ascophyllum nodosum* (Linnaeus), *Fucus vesiculosus* Linnaeus и *Fucus distichus* Linnaeus (Таб8л. 3). Узкая полоса, плотных зарослей этих видов представлена повсеместно на нижней части среднего горизонта каменистой литорали. Сообщество, связанное с поясом фукоидов более или менее однотипно воспроизводится в разных частях акватории [@naumov2001benthos], за исключением самых опресненных участков. В этом сообществе, помимо самих фукоидов, представлены в большом количестве мидии (*Mytilus edulis*, *M.trossulus*) и брюхоногие моллюски (*Littorina saxatilis*, *L. obtusata*). В зарослях фукоидов также многочисленны равноногие раки *Jaera* spp. и бокоплавы *Gammarus* spp. 

На илисто-песчаном грунте, подстилающем заросли фукоидов, обычно представлены элементы соответствующего сообщества, прдставленного за пределами пояса фукоидов (см. ниже, раздел “Cообщество илисто-песчаного грунта на литорали”).

Рыбы используют пояс фукоидов в качестве рефугиума во время отлива. Здесь пережидают период малой воды бельдюга и маслюк. Кроме того на таломах фукоидов откладывает икру трехиглая колюшка (см. выше).  

**Таблица 3.** Плотность поселения (экз/м^2^) и биомасса (г/м^2^) наиболее обильных видов, связанных с зарослями фукоидов на литорали Кандалакшского залива (отчетам ЗИН РАН за 2005-2007 и 2009-2010 гг, @zin2005; @zin2006; @zin2007; @zin2009; @zin2010).

**Сообщество илисто-песчаного грунта на литорали**

На среднем и нижнем горизонтах литорали в кутах небольших бухт и на закрытых от прибоя побережьях формируются, обычно небольшие по площади, илисто-песчаные пляжи. Наиболее крупные пляжи в зоне прохождения фарватера представлены на о. Б.Ломтишный, о. Луда Девичья, о. Ряшкове, на некоторых участках материка. В районе непосредственно соседствующем с портом «Витино» такие пляжи представлены в губе Коровья (о. Олений) и на литорали о. Телячий. Для таких пляжей характерно формирование плотных поселений полихет-пескожилов (Arenicola marina). Эти животные, как правило, не попадают в стандартные пробоотборники и данные по их обилию могут быть получены только косвенным методом, например через учет обилия их выбросов. В среднем на квадратный метр таких пляжей приходится 38 ± 2,3 выбросов (по данным архивов Кандалакшского заповедника). Помимо пескожилов на таких пляжах обычно многочисленны двустворчатые моллюски *Macoma balthica* (Табл. 4). Высокую плотность поселения демонстроируют брюхоногие моллюски (*Peringia ulvae*), олигохеты (*Tubificoides benedii*) и полихеты-трубкостроители (*Pygospio elegans*, *Fabricia stellaris*, *Dipolydora quadrilobata*, *Spio theeli*).

Виды, входящие в состав этого сообщества составляют кормовую базу для молоди речной камбалы [@polozov1992; @goltsev1994]. Отчасти этот тип сообществ снабжает пщей и молодь трехиглой колюшки [@shunkina2001], которая использует литоральный бентос в качестве источника пищи во время малой воды, держась в литоральных лужах [@demchuk2017]. Камбалы небольшого размера (длина тела 1 - 31 см) постоянно держаться над илисто-песчаными пляжами и вовремя прилива или остаются при отливе в литоральных лужах. Основными пищевыми объектами для камбал служат личинки Chironomidae, бокоплавы (*Gammarus* sp.) и пескожилы  (*Arenicola marina*).

**Таблица 4.** Средняя плотность поселения (экз./м^2^) и биомасса (г/м^2^) видов демонстрирующих наибольшие показатели обилия в сообществе илисто-песчаного литорального пляжа в вершине Канадалкшского залива (По архивным данным Кандалакшского заповедника).


**Сообщества мидиевых банок и друз**

Плотные скопления мидий, крепящихся как гравийно-галечному грунту, так и к друг другу, представлены на литорали и в верхнй сублиторали вершины Кандалакшского залива в виде локальных пятен различной площади. Эти сообщества приурочены к местам с быстрым течением и пологим дном (мысы, корги, мелководные проливы). Поселения формируются двумя видами: *Mytilus edulis* Linnaeus и *M. trossulus* Gould. 

Мидии, будучи сильными эдификаторами, создают своеобразную среду, которая населяется далеко не всеми обитателями литорали и верхней сублиторали [@khaitov2013life]. Среди скоплений мидий присутствуют либо виды, способные активно перемещаться (брюхоногие моллюски, немертины, Табл. 5), либо малоподвижные виды, развитие которых не связано с планктонной стадией, уязвимой для фильтрационной активности мидий (в первую очередь олигохеты *Tubificoides benedii*). Эти сообщества в районе прохождения факрватера представлены в следующих местах (Рис. 25):

▪Юго-восточный мыс о.Ряшкова; 

▪Литораль материка, луд и корг в сверо-западной части Западной Ряжковой салмы;  

▪Практически повсеместно на отмелях в районе островов Ломтишных.   



**Рисунок 25.** Расположение мидиевых банок на литорали участков, прилегающих к походному фарватеру. Карта построена на основе наблюдений в разные годы. Поскольку мидиевые банки очень динамичные системы, то их расположение может меняться год от года.


**Таблица 5.** Средняя плотность поселения (экз./м^2^) и биомасса (г/м^2^) видов демонстрирующих наибольшие показатели обилия в мидиевых банках Канадалкшского залива (По архивным данным Кандалакшского заповедника).




**Заросли ламинарии**

Формирование этого типа сообществ определяется поселениями бурой водоросли *Saccharina latissima* (Linnaeus), которая крепится к твердым субстратам ризоидами, от которых берет начало черешок, дистальная часть которого формирует платину, длина которой может достигать нескольких метров.  Заросли ламинарии приурочены к верхней части сублиторали (до глубины около 10 м). В районе прохождения фарватера этот тип сообществ занимает обширные площади  (Рис. 26). Заросли ламинарии окаймляют практически все острова и склоны берегов материка. Однако наиболее обширные заросли представлены в пространстве между островами Ряшков, Девичья Луда, Большой и Малый Ломтишные. Обычно в зарослях ламинарии формируется довольно сложный комплекс относительно независимых друг от друга сообществ: сообщества ризоидов ламинарии, сообщества обрастателей черешка и пластины водорослей и сообщества илистого грунта, который обычно скапливается в местах поселения ламинарии. Плотности поселения и биомассы наиболее обильных видов, населяющих ризоиды ламинарии приведены в таблице 6.




**Рисунок 26.** Распределение зарослей ламинарии в районе прохождения фарватера.


**Таблица 6.** Средняя плотность поселения (экз./м^2^) и биомасса (г/м^2^) видов демонстрирующих наибольшие показатели обилия в ризоидах ламинарии в районе прохождения фарватера. Для средних приведены стандартные ошибки. (По архивным данным Кандалакшского заповедника)

Количественных оценок обилия обитателей пластин и черешков ламинарии нет. В илистом грунте, окружающем заросли ламинарии, как правило присутствуют сообщества близкие по своей структуре к сообществам мелководных илов (см. ниже).

В зарослях ламинарии находят кормовую базу треска и навага. Однако, по данным отловов, в этих сообществах, как правило, встречаются достаточно мелкие особи этих видов рыб. 


**Сообщество мелководных илов**

Эти сообщества формируются в сублиторали на глубинах до 20 м в участках со слабым течением. Как правило, участки, на которых представлено данное сообщество, приурочены к межостровьям в шхерах, в сублиторали мелководных губ и на участках, находящихся в «гидродинамической тени» (в ямах, между порогами, экранирующими течения). В этих сообществах численности доминируют роющиеся формы: полихеты (*Terebellides stroemi*, *Scoloplos armiger*, *Aricidea nolani*, *Micronephthys* sp.), бокоплавы (*Pontoporeia femorata*, *Atylus carinatus*) и кумовые раки (*Diastylis glabra*, *D. sulcata*, *D. scorpiodes*). В некоторых районах в таких сообществах значительную плотность поселения демонстрируют  полихеты-трубкостроители (сем.Maldanidae, Spionidae). По биомассе в таких сообществах доминируют двустворчатые моллюски из семейства Astartidae (*Tridonta borealis*, *T. elliptica*), *Serripes groenlandicus*, *Ciliatocardium ciliatum*,  *Macoma calcarea* или *Macoma balthica*. В районах, находящихся в контакте с зарослями ламинарии в этом сообществе возрастает роль полихет *Pista maculata*, которые строят длинные переплетающиеся трубки. 

В районе фарватера этот комплекс отмечен в Южной и Северной губе о. Ряшкова, в пространстве между островами Луда Девичья, Куричек, Большой и Малый Ломтишные (Рис. 27). Важно отметить, что пятна этого типа сообществ представлены в том числе и на фарватере (Рис. 27). Именно эти сообщества потерпел наиболее сильное нарушение после изменения гидродинамического режима вследствие дноуглубительных работ, проведенных в августе 2007 г.
 
Роль этих сообществ в формировании кормовой базы рыб неизвестна, но известно, что любительский лов рыбы на участках, где оно представлено крайне неэффективен. Виды, формирующие это сообщество лишь эпизодически встречаются в питании трески. 


**Рисунок 27.** Расположение усатков, на которых отмечено сообщество мелководных сублиторальных илов. 


**Таблица 7.** Средняя плотность поселения (экз./м^2^) и биомасса (г/м^2^) видов наиболее типичных для сообществ мелководных илов. (По архивным данным Кандалакшского заповедника)


**Сообщество глубоководных илов**

Эти сообщества формируются в глубоких ямах (более 20 м), в которых задерживается холодная зимняя водная масса. Виды комплекса, описанного выше, здесь также могут быть представлены, но их обилие заметно ниже. Наиболее заметные отличия касаются обилия двустворчатых моллюсков. В этом комплексе ведущую роль играют двустворки *Portlandia arctica*. 

В районе прохождения фарватера эти сообщества представлены в северо-западной части Западной Ряжковой салмы (Рис. 28). Кроме того это сообщество было отмечено на выходе из Палкиной губы (Отчеты ЗИН за 2005-2007 гг, @zin2005; @zin2006; @zin2007). Наиболее обильным по плотности поселения в этом сообществе являются двустворчатые моллюски *Portlandia arctica* и полихеты *Aphelochaeta marioni*. По биомассе преобладают двустворчатые моллюски  Portlandia arctica и *Macoma calcarea* (Табл. 8).



**Рисунок 28.** Расположение участков, на которых отмечено сообщество глубоководных сублиторальных илов. 

**Таблица 8.** Средняя плотность поселения (экз./м^2^) и биомасса (г/м^2^) видов наиболее типичных для сообществ мелководных илов. (По архивным данным Кандалакшского заповедника)


**Сообщество зарослей багрянок**

Это одно из самых богатых видами донных сообществ Белого моря, отмечено 315 таксонов [@mikhaylova2019diversity]. Оно формируется в нижней части фитали на глубинах от 7 до 23 м. Фон в этом сообществе создают пластинчатые красные водоросли, в первую очередь, *Phyllophora* sp., *Odonthalia dentata* (Linnaeus) и *Phycodrys rubens* (Linnaeus). Заросли багрянок располагаются ниже зарослей ламинарии и формируют характерные пояса, окаймляющие сублиторальные склоны в местах с высокой гидродинамической напряженностью (прежде всего салмы, Рис. 29). 



**Рисунок 29.** Распределение зарослей багрянок в районе прохождения фарватера. 

Пояс багрянок вплотную подходит к фарватеру и даже в нескольких местах пересекает его. Это сообщество представлено в том числе и на порогах, которые мешают судоходству. С очевидностью заросли багрянок исчезнут в результате дноуглубления, призванного убрать упомянутые пороги. 

Роль этого типа сообществ в формировании пищевой базы рыб в вершине Кандалакшского залива никогда не оценивалась. Можно лишь предположить, что она невелика, так как большинство обитателей зарослей багрянок - это неподвижные эпибионты (Табл. 9, @mikhaylova2019diversity), которые практически никогда не отмечаются в питании трески. 

**Таблица 9.** Биомасса (г/м2) наиболее обычных видов, представленных в сообществах, связанных с зарослями багрянок в двух участках Кандалакшского залива Белого моря (из @mikhaylova2019diversity с изменениями). 


**Сообщество гравийно-галичных промытых грунтов**

Это сообщество формируется на глубине 15-25 м на участках, где наблюдаются быстрые приливно-отливные течения. Такие условия складываются в узких относительно глубоководных проливах, например, в Восточной и Западной Ряжковой салмах (Рис. 30). По последней проходит фарватер и в первую очередь здесь необходимо проведение дноуглубительных работ. 
Поскольку это сообщество формируется приблизительно в том же диапазоне глубин, что и сообщество мелководных илов, то в сообществах гравийно-галичных промытых грунтов могут быть найдены виды характерные и для заиленных участков (роющиеся и строящие трубки полихеты, зарывающиеся в грунт моллюски, бокоплавы и кумовые раки). Степень сходства зависит от уровня заиленности тех участках проливов, которые находятся в «гидродинамической тени» (см. выше). При ослаблении течений за счет порогов и ям могут формироваться сообщества очень близкие к сообществам мелководных илов. Однако в остальных участках, где быстрые течения вымывают ил, облик сообщества иной. Здесь на лишенном илистого покрова гравии и гальке богато представлено сообщество обрастателей. К числу видов, которые формируют облик этого сообщества относятся усоногие раки *Balanus balanus* и *B.crenatus*, плеченогие *Hemithiris psittacea*, крупные гидроидные полипы *Tubularia* и несколько видов асцидий (*Boltenia echinata*, *Stiela rustica*, несколько видов *Molgula*). На поверхности грунта в этом сообществе в большом количестве встречаются иглокожие: офиуры (*Ophiopholis aculeata*, *Ophiura robusta*) и морские звезды (*Asterias rubens*, *Crossaster papposus*, *Henricia* sp.).






**Рисунок 30.** Расположение участков, на которых отмечено сообщество промытого гравийно-галичного грунта. (По архивным данным Кандалакшского заповедника)


Всего в районе прохождения фарватера было отмечено 285 таксона макрозообентоса. Указать точное количество видов макрофитов пока не представляется возможным, так как детальный анализ альгофлоры в на данной акватории ни разу не проводился. На данный момент в районе прохождения фарватера отмечено 16 таксонов сублиторалных многоклеточных водорослей. 

Анализ графика накопления числа отмеченных таксонов (Рис. 31) свидетельствует о том, что, не смотря на большое количество проб (за весь период наблюдений здесь было взяты пробы на 148 дражных и 3 дночерпательных станциях), видовой список полностью не исчерпан. Это связано прежде всего с высоким пространственным разнообразием сообществ и отчасти с изменениями, которые произошли в сообществе за период мониторинга (см. ниже).  




**Рисунок 31.** Накопленное число видов сублиторального бентоса в районе прохождения фарватера. Серая область - 95% доверительный интервал. (По архивным данным Кандалакшского заповедника и отчетам ЗИН РАН за 2006 и 2007 гг., @zin2006; @zin2007)


Мониторинг донного сообщества в районе прохождения фарватера по Западной Ряжковой салме позволил заметить следующее. Дноуглубительные работы 2007 г. привели к существенным изменениям в структуре сообщества. Видовое разнообразие, оцененное с помощью коэффициента Шеннона, значимо сократилось (Рис. 32, A). Поскольку мониторинг, проводимый Кандалакшским заповедником основан на полуколичественных дражных сборах, не дающих информации о плотностях поселения вида, то оценить изменение обилия организмов можно только косвенным путем. Так, если анализировать общее количество животных, попавших в пробы (Рис. 32, B), то видна тенденция к снижению этого показателя. В год, следующий за дноуглублением, в точке взятия проб несколько раз в драге обнаруживались лишь окатанная галька, вообще лишенная животных. Эти результаты позволяют считать, что дноуглубительные работы существенно изменили характер течений в Западной Ряжковой салме. Здесь уже не обнаруживается илистых полей, ранее присутствовавших на траверзе о. Куричек, где происходит отбор мониторинговых проб. Дальнейшее расширение подобных работ, с очевидностью, усугубит это воздействие. 





**Рисунок 32.** Многолетняя динамика сообщества гравийно-галичного грунта в районе прохождения фарватера по Западной Ряжковой салме. **A.** Изменение видового разнообразия (индекс Шеннона). **B.** Изменение общего числа животных, отмеченных в пробах. На обоих панелях приведены линии регрессии с 95% доверительными интервалами. Горизонтальная пунктирная линия демонстрирует многолетнее среднее соответствующего параметра. Стрелка указывает на время дноуглубительных работ.  (По архивным данным Кандалакшского заповедника). 

Оценки обилия видов, входящих в состав этого сообщества (Табл. 10), проведены на основе данных отчетов ЗИН РАН за 2006-2007 гг [@zin2006; @zin2007]. Наиболее обильным по плотности поселения представителями этого сообщества являются полихеты (*Chaetozone setosa*, *Galathowenia oculata*) и двустворчатые моллюски (*Macoma calcarea*). По биомассе доминируют *M. calcarea* и офиуры (*Ophiura robusta*).

Таблица 10. Средняя плотность поселения (экз./м^2^) и биомасса (г/м^2^) видов наиболее типичных для сообщества промытого гравийно-галичного грунта в Западной Ряжковой салме. (По материалам отчетов ЗИН РАН за 2006-2007 гг., @zin2006; @zin2007)


Сообщество промытого гравийно-галичного грунта, по-видимому, играет значительную роль в откорме бентоядных рыб. Наблюдения над маломерными судами, с которых осуществляется любительский лов рыбы в вершине Кандалакшского залива, показал, что наиболее часто они располагаются над участками, где представлен именно этот тип сообществ. Вскрытие кишечников рыб, отловленных в районе прохождения фарватера, показал, что основу питания рыб составляют офиуры. Сопоставление пищевого спектра беломорской трески [@yershov2010_changes] и полосатой зубатки  [@yershov2010_structure] показало, что часть видов, составляющих ядро сообщества промытого гравийно-галичного грунта в районе Западной Ряжковой салмы (в основном офиуры и моллюски), входит в рацион питания этих бентоядных рыб. 


# Ожидаемые угрозы для биосистем

В связи с предполагаемыми дноуглубительными работами, ожидаются следующие негативные воздействия на биосистемы, представленные в районе прохождения фарватера. Самое мощное воздействие ожидается непосредственно в результате дночерпания. Донные сообщества в районе воздействия, с очевидностью, будут уничтожены. Помимо этого ожидается изменение характера гидродинамических процессов в районе фарватера. Опыт предыдущих дноуглубительных работ, проведенных в зоне фарватера в 2007 г., показал, что в результате этого воздействия степень промытости грунта в районе фарватера резко возрастает. Фактически илистое пятно в центральном желобе Западной Ряжковой салмы (Рис. 27) исчезло. Расширение зоны дноуглубительных работ усугубит эти изменения, что с высокой вероятностью может сказаться и на популяции трески. Более свободное перемещение водных масс может также сказаться и на характере течений и, как следствие, на паттерне распределения солености вдоль Карельского берега Ожидается, что степень опреснения акватории повысится. Еще одним ожидаемым риском является влияние отвала грунта, которое планируется в непосредственной близости от границ Кандалакшского Заповедника. Этот процесс может привести к повышению мутности воды и накоплению мелкодисперсных фракций грунта на близлежащих мелководьях и литорали. Биологические последствия такого влияния пока предсказать трудно. 



Использованные источники 
